### ISSUE TITLE
Development Plan with GAT

### ISSUE THREAD

**Issue by rigelrozanski** [jblindsay/whitebox-tools#1]
GREAT WORK JOHN! woot. 

Just curious if you plan to consolidate any common functions of whitebox-GAT to whitebox tools? Is this already the case that Whitebox-GAT calls rust whitebox-tools? I'm excited about this project - 
myself I'd like to eventually be able to call rust these rust functions directly for go-code.. can just use go as a scripting language and call directly into the Whitebox-Tools binary for the time being... Do function calls return json output for non-file output? I imagine that there are a number of functions which have small amount of output, it'd be nice if this was machine parseable. 

go john go!

**Comment by jblindsay** [comment]
The current version of Whitebox-GAT does not call WhiteboxTools functions as of yet. The plan is to finish porting all of the Whitebox-GAT tools to this new Rust library, and then use it as the back-end in one of the future versions of Whitebox-GAT. I still have some work to do in porting tool over to Rust though.

The tools that output non-raster/vector/LAS outputs generate html files. This includes tools that output tabular data and charts, which include interactive SVG histograms, scattergrams, and line graphs.
