### ISSUE TITLE
Unsupported TIFF file type produced from WBT.breach_depressions(input, output, fill_pits=False)

### ISSUE THREAD

**Issue by jmpmcmanus** [jblindsay/whitebox-tools#101]
When I run breach_depressions, on a DEM, it outputs a tif file that produces an error when using it as input to TauDEM d8flowdir. The output from d8flowdir is:

Unsupported TIFF file type or filetype not known when reading nodata tag.  sampleFormat = 3, dataSizeFileIn = 8.

I can read the file with rasteio, and qgis, so it's a readable tiff. I ran WBT.breach_depressions using different DEM tif files and it always produced a output tif tile that will produce an error in d8flowdir.

I can run WBT.burn_streams_at_roads, using the same DEM I used as input to WBT.breach_depressions, and it will produce a tif file that will not produce an error when using it as input to d8flowdir.

Jim

**Comment by jblindsay** [comment]
If you can display the file in QGIS then I suspect the error lies on the TauDEM side. Perhaps report the issue there. Also, unless you have a good reason to be using the BreachDepressions tool, you're probably better off using the LeastCostBreach tool instead.

**Comment by jmpmcmanus** [comment]
WBT.breach_depressions produces a tif file with float64 values, which TauDEM d8flowdir interprets as an invalid tif. I converted the tif file to float32, and it worked. I will check with the people who developed TauDEM to see why their code interprets float64 tif files as invalid.

Thanks for the quick response, and the tip on LeastCostBreach.

**Comment by jblindsay** [comment]
@jmpmcmanus I just committed code that will ensure that the output of the D8 and FD8 pointer tools is saved as 8-bit unsigned integers (bytes). The previous code simply copied the data type from the input DEM, which was probably unnecessary. Unfortunately, this change won't be available until the next release. You may always compile the source code however if you need it before then. It's quite simple to compile.
