### ISSUE TITLE
Relationship table for nested basins (Isobasins tool)

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#103]
It would be useful if the tool Isobasins could produce a relationship table for the delimited watersheds. In other words, I would like to know, for each watershed, in which other one they flow. For example, if I have four watersheds and that `#1` flow into `#2` than itself flow into `#3` but `#4` flow into none I would like a simple TXT/CSV file with a table like:

| Upstream | Downstream
| ------------- |:-------------:|
| 1   | 2 |
| 2   | 3 |
| 3   | 0 or NA |
| 4   | 0 or NA |

With that in hand, I can use other tools to know that `#3` is also downstream of `#1` and that if something changes in `#1`, it could have an effect on both `#2` and `#3`.

I'm currently writing something in Python to do that using the flow pointer, flow accumation and isobasins rasters but I'm pretty sure it will be quite inefficient compared to a built-in solution.

**Comment by jblindsay** [comment]
Would the UnnestBasins tool be useful for this?

**Comment by jfbourdon** [comment]
Thanks for the suggestion, I justed tried it and I think it could do it but it will not be straightforward, at least for my purpose:
- I need a script to generate the pour points first (I have to do this anyway... but it would be nice if `Basins` and `Isobasins` could optionally output pour points).
- It generates one raster by nested level (could be a problem with several levels with a very large raster).
- I will need another script to loop through the rasters and add their value of the pour points under.

I'll try something and see...

**Comment by jblindsay** [comment]
I just committed an updated version of the Isobasin tool that can optionally output a CSV file containing an upstream/downstream connection table. If you wouldn't mind testing the tool and reporting any issues that you run into with it. I have done a brief test with the sample Vermont DEM and it seemed to work well.

**Comment by jfbourdon** [comment]
Works great, no issue to report. Thanks!
