### ISSUE TITLE
How Can I Caught errors in python .

### ISSUE THREAD

**Issue by aman-appcino** [jblindsay/whitebox-tools#108]
Hi, The library is awesome and I am using it in my projects can you please tell me how to caught errors of rust in python using try catch block or any other method.
Thanks

**Comment by aman-appcino** [comment]
Hi,
All function always return 0. Either it is a case of error or case of successful run. 
please resolve this issue asap or provide other method to check error during process in python.

**Comment by jblindsay** [comment]
@aman-appcino Errors are thrown by the underlying Rust code in the WBT backend. The WBT Python API is simply a thin wrapper around that. I have provided a mechanism for users to handle errors by providing a custom call-back function for every tool. Please see [Handling tool output](https://jblindsay.github.io/wbt_book/python_scripting/tool_output.html) in the User Manual for more details.

**Comment by aman-appcino** [comment]
I have tried with the same as well.
But callback method is never called in any of the function which I am using.
can you please provide the solution for the same.
Thank you

**Comment by aman-appcino** [comment]
@jblindsay 
Any Solution for the above query.
I am unable to caught exception or errors.
Callback methods never called in any of the function in python.
Thank you

**Comment by jblindsay** [comment]
I'm not sure what to tell you, callback function do work, I use them all the time myself as do several people who work with me. Can you perhaps give a specific code example of where things are not working for you?
