### ISSUE TITLE
Many hydrology tools not writing output files in ArcGis Pro

### ISSUE THREAD

**Issue by lukejzw** [jblindsay/whitebox-tools#111]
Hi, I've been trying to run some of the hydrology tools in ArcGis Pro. While the models appear to be running to completion, they fail to save an output file to the disk which is a bit odd. Any idea why this happening?

Luke

**Comment by giswqs** [comment]
Are you using the [WhiteboxTools-ArcGIS](https://github.com/giswqs/WhiteboxTools-ArcGIS) frontend? If yes, please open an issue [here](https://github.com/giswqs/WhiteboxTools-ArcGIS/issues).

**Comment by lukejzw** [comment]
Thank you, you are correct. I will post it there
