### ISSUE TITLE
request for porting "topological breach burn" to WhiteboxTools

### ISSUE THREAD

**Issue by fluviotect** [jblindsay/whitebox-tools#120]
I'd like to include it in one of my Python processes.

Cheers,
Will

**Comment by fluviotect** [comment]
I'm still interested in this if it hasn't been addressed.

**Comment by Afrancioni** [comment]
Hello, @fluviotect 

We are in the works about potentially porting this tool. Thank you for your patience.

**Comment by vonStadarhraun** [comment]
Any news on this?

**Comment by Afrancioni** [comment]
Hello, 
Apologies for replying to this so late but, the TopologicalBreachBurn tool has been made available https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#TopologicalBreachBurn
