### ISSUE TITLE
'main' panicked on example

### ISSUE THREAD

**Issue by maulanarachmat** [jblindsay/whitebox-tools#124]
I tried to use your example usage

`whitebox_tools.exe -r=lidar_info --cd ="D:\las_data\" -i=all_input.las --vlr --geokeys`

I got this error:
thread 'main' panicked at 'Tool run with no parameters.', src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How to solve this,
Thank You

My system :
Windows 10

**Comment by jblindsay** [comment]
It seems that you are running WhiteboxTools from the [command prompt](https://jblindsay.github.io/wbt_book/command_prompt.html). That's fine, but if you do so, you need to use the actual tool names and not the tool names provided by the Python API. For example, the actual name of the tool you are using is [**LidarInfo**](https://jblindsay.github.io/wbt_book/available_tools/lidar_tools.html#LidarInfo), and not **lidar_info**. Python uses snake_case, while Rust, which WBT is programmed in, uses CamelCase.

**Comment by Afrancioni** [comment]
This question seems better suited to ask within our Google Group. You can access this group [here](https://groups.google.com/u/1/g/whiteboxtools). I am also going to close this issue as @jblindsay has provided a solution. If @jblindsay's solution did not work, I can re-open this issue.
