### ISSUE TITLE
Conditional Evaluation

### ISSUE THREAD

**Issue by mapninja** [jblindsay/whitebox-tools#125]
This is a pretty powerful tool, available in WhiteboxGAT. Would love to see it the new WBT release so there is a stable Conditional for QGIS.

**Comment by jblindsay** [comment]
It's on my wish-list as well. There are certain aspects to this tool that make it very difficult to re-implement in WBT. In particular, it requires a dynamic scripting language.

**Comment by jblindsay** [comment]
I just pushed the new ConditionalEvaluation tool. It will appear in v1.6.0 when it is released. You can compile from source if you would like to play with the tool before then. I'm closing this issue now.
