### ISSUE TITLE
Python frontend doesn't recognize function arguments.

### ISSUE THREAD

**Issue by NO645** [jblindsay/whitebox-tools#134]
The extract_raster_values_at_points() function doesn't seem to recognize that it is being provided with all of the required arguments. Variables rasterr and pointss are strings pointing to tif and shp file locations respectively.

```
>>>results = wbt.WhiteboxTools.extract_raster_values_at_points(rasterr, pointss, out_text=True)
Traceback (most recent call last):

  File "<ipython-input-14-b1608e066bee>", line 1, in <module>
    results = wbt.WhiteboxTools.extract_raster_values_at_points(rasterr, pointss, out_text=True)

TypeError: extract_raster_values_at_points() missing 1 required positional argument: 'points'
```

I'd ask at the other repository but it specifically says to come here for questions related to the functions themselves.

Thank you.

**Comment by giswqs** [comment]
I just tested the tool, and it works fine. 
![](https://i.imgur.com/YD3L6nR.png)

**Comment by Afrancioni** [comment]
I am going to close this issue as it seems that @giswqs has confirmed the tool works fine. I can re-open this issue if need be.
