### ISSUE TITLE
[feature request] support geopackage as vector format

### ISSUE THREAD

**Issue by CWen001** [jblindsay/whitebox-tools#136]
Greetings. Geopackage (.gpkg) is a widely-used vector format and database container in open GIS communities. Compared to shapefile format, it supports long column names and more efficient data storage.

Is it possible that whitebox-tools can consider adding support for geopackage as the vector format? Thank you very much in advance.

**Comment by jblindsay** [comment]
I'm sorry but supporting Geopackages would add a dependency of SQLite, which is contrary to the development goals of the project. As such it is very unlikely that WBT will support this file format in the future.
