### ISSUE TITLE
Wetness index - should use slope in radians not degrees?

### ISSUE THREAD

**Issue by jrmosedale** [jblindsay/whitebox-tools#138]
The documentation states slope should be calculated in degrees, but this should be radians (otherwise a slope of 10 will give a higher TWI than a slope of 1)

**Comment by jfbourdon** [comment]
The conversion from degrees to radians is taken care of inside the script:
https://github.com/jblindsay/whitebox-tools/blob/db8423fd1e9b884ab9c6cd11eff7309c1e892a0a/src/tools/terrain_analysis/wetness_index.rs#L244

**Comment by jblindsay** [comment]
@jfbourdon is correct, I designed this tool to take slope in degrees as the input since that is most often the output of GIS-based slope tools, and then internally converts the slope to radians.
