### ISSUE TITLE
status 101, input has to be a file.path?

### ISSUE THREAD

**Issue by chamesoul** [jblindsay/whitebox-tools#139]
Hello, 

I'm new to all this (just created my account on github in order to find an answer about my issue, and I apologize in advance for any mistake I would be making (not a native english speaker either))

My objective is to create a flow accumulation raster from a flow direction raster, but I wanted first to check from a DEM.

I'm having a hard time using "wbt_d8_flow_accumulation", my code gives me back the "status 101", I searched and found this previous issue (https://github.com/jblindsay/whitebox-tools/issues/83)

I used the code that was given as a test by @giswqs  : 

```
library(whitebox)
# Set input raster DEM file
dem <- system.file("extdata", "DEM.tif", package="whitebox")
# Run tools
wbt_feature_preserving_smoothing(dem, "./smoothed.tif", filter=9, verbose_mode = TRUE)
```

It works fine, that's good, but then comes my question, because the same "error" comes up with this code for dem1 (I just copy/pasted the DEM file into my project directory (it works fine for dem2) : 
```
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package="whitebox")
dem1 <- raster("DEM.tif")
dem2 <- file.path(getwd(),"DEM.tif")

output <- file.path(getwd(), "output.tif")
output1 <- file.path(getwd(), "output1.tif")
output2 <- file.path(getwd(), "output2.tif")

wbt_d8_flow_accumulation(dem, output)
wbt_d8_flow_accumulation(dem1, output1)
wbt_d8_flow_accumulation(dem2, output2)
```

So I was wondering, although, in the "help" given on RStudio for the function, the input is said to be "Input raster DEM or D8 pointer file", what is considered as a file is the character path to this file? (If it's a basic question I apologize)

Moreover, when I try it with my DEM, with this code 
```
dem_proj <- file.path(getwd(),"mnt1m_large.tif")

output_proj <- file.path(getwd(), "output_proj.tif")

wbt_d8_flow_accumulation(dem_proj, output_proj)
```
I got this output
`[1] "d8_flow_accumulation - **********************************************************************************"`
which is different from the example, I was wondering if all those stars had a meaning.
Also the raster in output doesn't give anything like the one produced with the example file (no flow, only some dots here and there).  That might comes from my DEM file (1m resolution) but I don't see how. 

Thanks

**Comment by jfbourdon** [comment]
The R library `whitebox` is only a frontend, nothing is really happening in R itself but rather in the the compiled binary. So all arguments given to each tool, must be either numeric, character or logical. By doing `dem1 <- raster("DEM.tif")`, you are trying to pass a RasterLayer that is interpreted as `as.character(dem1)`. All raster and vector input/output should be given as full path instead of special R object.

```r
library(whitebox)
dem <- system.file("extdata", "DEM.tif", package="whitebox")
output <- file.path(getwd(), "output.tif")

# With R frontend
wbt_d8_flow_accumulation(dem, output)

# Without R frontend 
system(paste0(wbt_exe_path(),
             " --run=D8FlowAccumulation",
             " --input='", dem, "'",
             " --output='", output, "'"))


```

**Comment by chamesoul** [comment]
Oh I see, thanks for the explanation!
