### ISSUE TITLE
Pixel misalignment between original and resulting images

### ISSUE THREAD

**Issue by giswqs** [jblindsay/whitebox-tools#14]
Using the [testdata/DEM.tif](https://github.com/jblindsay/whitebox-tools/blob/master/testdata/DEM.tif), I noticed that the resulting images from most tools shifted half a pixel towards the lower-right corner. The issue can be reproduced using the script below. 
```
wbt = WhiteboxTools()
wbt.feature_preserving_denoise("DEM.tif", "smoothed.tif", filter=9)
wbt.breach_depressions("smoothed.tif", "breached.tif")
wbt.d_inf_flow_accumulation("breached.tif", "flow_accum.tif")
```

For example:
_DEM.tif_
CRS | EPSG:4326 - WGS 84 - Geographic
Extent | **664692**.0589773271931335,**4878903**.5508630042895675 : 686018.1474491551052779,4895827.5998771572485566
Pixel Size | 89.9835,-90.0215

_smoothed.tif_
CRS | EPSG:4326 - WGS 84 - Geographic
Extent | **664737**.0507251580711454,**4878858**.5400943495333195 : 686063.1391969859832898,4895782.5891085024923086
Pixel Size | 89.9835,-90.0215

diff = ~ 45 (half a pixel)

**Comment by jblindsay** [comment]
I believe that the [recently committed](https://github.com/jblindsay/whitebox-tools/commit/9ffeb39cc87da5363777c6595ffc452df8f6dd23) updates to the GeoTIFF reader/writer will correct this issue. If a TIFF is used as the input to a tool and a TIFF is also specified as the output, WhiteboxTools now simply copies the georef tags from input to output rasters.
