### ISSUE TITLE
Problem with Deflate compressed geotiff with predictors with ElevRelativeToMinMax

### ISSUE THREAD

**Issue by newcomb-d** [jblindsay/whitebox-tools#142]
Running Whitebox tools downloaded 3/16/2021 using the QGIS plugin on QGIS 3.16. using ElevRelativeToMinMax on  Gdal Deflate compressed Geotiff with Predictor=3 
Log result as follows: 

QGIS version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'ElevRelativeToMinMax' starting…
Input parameters:
{ 'dem' : 'E:/elevation/alamancedem05.tif', 'output' : 'E:/elevation/alamancedem05_relative_minmax.tif' }

WhiteboxTools command:
"C:/WhiteboxTools_win_amd64/WBT/whitebox_tools.exe" --run=ElevRelativeToMinMax --dem="E:\elevation\alamancedem05.tif" --output="E:\elevation\alamancedem05_relative_minmax.tif" -v
WhiteboxTools command output:
***********************************

* Welcome to ElevRelativeToMinMax *

***********************************

Reading data...

thread 'main' panicked at 'The GeoTIFF reader does not currently support floating-point predictors (PREDICTOR=3).', src\main.rs:72:21

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Execution completed in 21.31 seconds

The input file is a deflate compressed geotiff with predictors of size  953 Mb

**Comment by jfbourdon** [comment]
As the error message tells, _The GeoTIFF reader does not currently support floating-point predictors (PREDICTOR=3)_ and it doesn't seem that its support is on the roadmap (see #97).

You must convert your raster and use either `PREDICTOR=1` or no compression at all. You can easily do it with GDAL inside QGIS. Just export your raster using _Save As..._ in the contextual menu on your layer. Without adding any option, the resulting file will be uncompressed. If you want compression, under the _Create Options_ section, you can add the line `COMPRESS` (as Name) and `DEFLATE` (as Value).

You can also call directly GDAL by a command-line to compress with DEFLATE and predictor 1 (default): `gdal_translate -co COMPRESS=DEFLATE E:/elevation/alamancedem05.tif E:/elevation/alamancedem05_DEFLATE1.tif`
