### ISSUE TITLE
Vector Stream Network Analysis tool

### ISSUE THREAD

**Issue by sraul1** [jblindsay/whitebox-tools#145]
I am more of a front-end user so this may be quite a bit more difficult than I imagine, but I would love to see the Vector Stream Network Analysis tool get added to WBT. I use it all the time in WhiteboxGAT. Lots of good uses for the output (as shown in your 2019 paper on the WhiteboxGAT version). 

These are great tools you have developed, I am a big fan of them. Between WBT/GAT and Topotoolbox I rarely have to open ArcMap anymore.

**Comment by Afrancioni** [comment]
Hello @sraul1 ,

The VectorStreamNetworkAnalysis Tool has been officially added to WhiteboxTools (https://www.whiteboxgeo.com/manual/wbt_book/available_tools/stream_network_analysis.html#VectorStreamNetworkAnalysis). The tool is apart of the General Toolset Extension and requires a software license. You can see more about the General Toolset Extension [here](https://www.whiteboxgeo.com/whitebox-toolset-extensions/).
