### ISSUE TITLE
Deviation From Mean Elevation and Maximum elevation deviation are probably not working correctly

### ISSUE THREAD

**Issue by zm8597** [jblindsay/whitebox-tools#149]
Greetings,

We are developing RVT (Relief Visualization Toolbox) in Python and we would like to add your Multi-scale topographic position (MSTP) visualization to it. When we tried to program MSTP in python we ran into some issues. As we compared our results with Whitebox we found out that Deviation From Mean Elevation (DEV) and Maximum elevation deviation (DEV MAX) are probably not working as they should. We have tried convolutional kernel filter approach and summed area table approach. Results were always the same but different compared to the results from Whitebox. We used formulas from your article: DEV(D) = (z0 - zmD) / sD, where D is radius of kernel, z0 is center pixel value, zmD is mean of all kernel values, sD is standard deviation of kernel. We have also calculated DEV in ArcGIS Pro with focal statistic and raster calculator, and got similar results as in Python but diffrent than in Whitebox. You can check our python code here (https://github.com/EarthObservation/RVT_py/blob/master/rvt/vis.py#L1602).
I am also attaching some calculated samples of DEV calculated with Python, ArcGIS Pro and Whitebox (radius=5, DEM="test.tif"):
[tst_DEV_rad5.zip](https://github.com/jblindsay/whitebox-tools/files/6306271/tst_DEV_rad5.zip)

Best regards,
Žiga Maroh

**Comment by jblindsay** [comment]
Hello Žiga, I'm afraid that this is probably not the best outlet for this correspondence, since this is only intended for reporting issues (i.e. bugs) with WBT. I'm closing this now. Please feel free to repost your question either on the [Google Groups](https://groups.google.com/u/1/g/whiteboxtools) forum or email support@whiteboxgeo.com directly. Thank you kindly.

**Comment by zm8597** [comment]
This is bug, two raster visualization functions not computing the correct results (as described in article and documentation). I will write an email. Thank you, all the best.

**Comment by jblindsay** [comment]
It looks like I was too quick to close this issue and so I'm re-opening it now. I'm at a particularly busy period at the end of my semester, but will hopefully have more time to look into this soon.

**Comment by zm8597** [comment]
Sorry to be a bother. I misunderstood Whitebox GAT with WhiteboxTools. I have tested everything with WhiteboxTools and I have got the expected output. All the best.
