### ISSUE TITLE
Open ".dep" extension file (in Python)

### ISSUE THREAD

**Issue by nikzadb** [jblindsay/whitebox-tools#150]
Hi,

I have been given a point cloud file with ".dep" extension. I am a Python user and I have an issue understanding how to open the ".dep" file in whitebox-tools (in python) and possibly change it to one of the Point Cloud extensions (such as las).

Really appreciate your help

**Comment by jblindsay** [comment]
Hi @nikzadb This is not a user forum for question but rather it is strictly for reporting issues and bugs in the software. Please use the [Google Groups](https://groups.google.com/u/1/g/whiteboxtools) forum for general questions about the software. Thanks.
