### ISSUE TITLE
no link to example Python data file (St. Elis Mountains)

### ISSUE THREAD

**Issue by evanmascitti** [jblindsay/whitebox-tools#152]
Hello Dr. Lindsay - I am working through the user manual on Python scripting. In [section 3.1.4](https://jblindsay.github.io/wbt_book/python_scripting/example.html) the user is instructed to:

>Visit the Geomorphometry and Hydrogeomatics Research Group website and download the St. Elis Mountains and Gulf of Alaska sample data set (StElisAk.las) from the WhiteboxTools section of the site. This file contains a LiDAR point cloud.....

I cannot find an actual link to the file anywhere on the website. Could you please update the documentation with a direct hyperlink?

**Comment by hiroyuki-sato** [comment]
Hello, @evanmascitti 

JFYI, I asked the same question on Twitter.
https://twitter.com/whiteboxgeo/status/1417852570027053061?s=20

**Comment by Afrancioni** [comment]
Hello @evanmascitti , 

We have now hosted that file on our website. It can be found via the following link (https://whiteboxgeo.com/sample_data/StElisAk.zip). We have hosted that file on our website now and will will update the user manual to reflect the new location of this file when we release the next version of WhiteboxTools.

**Comment by Afrancioni** [comment]
Closing this issue as there is now a working link to this file.
