### ISSUE TITLE
Watershed Tool - thread 'main' panicked at 'Unrecognized raster type'

### ISSUE THREAD

**Issue by tombrennan06** [jblindsay/whitebox-tools#153]
I get the following error when running the Watershed tool on Windows 10, QGIS 3.18.1, WhiteboxTools version 1.4.0, WhiteboxTools for Processing plugin version 1.2.0

I can replicate the issue at the WhiteboxTools command line, so it seems to be specific to WhiteboxTools, and not some issue with the plugin or QGIS.

```
E:\geodata>"C:\misc\WBT\whitebox_tools.exe" --run=Watershed --d8_pntr="E:\geodata\canyons\d8ptr.tif" --pour_pts="E:\geodata\canyons\outlet.shp|layername=outlet" --esri_pntr="False" --output="E:\geodata\canyons\output.tif" -v
************************
* Welcome to Watershed *
************************
Reading data...
thread 'main' panicked at 'Unrecognized raster type', src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The D8 Pointer file was produced by WhiteboxTools.

When I replaced the Pour Points vector with the equivalent raster (below), the tool ran correctly. So possibly there is an issue with the Pour Points not correctly handling vector input?
```
"C:\misc\WBT\whitebox_tools.exe" --run=Watershed --d8_pntr="E:\geodata\canyons\d8ptr.tif" --esri_pntr="False" --output="E:\geodata\canyons\output.tif" --pour_pts="E:\geodata\canyons\outlet.tif" -v
```
Test input files I used are attached
[watershed.zip](https://github.com/jblindsay/whitebox-tools/files/6369508/watershed.zip)

**Comment by jblindsay** [comment]
I think the error is likely the result of this input parameter **"outlet.shp|layername=outlet"**. The tool only wants a file name, which must be a shape file. The additional `|layername=outlet` will cause an unrecognized file type error.

**Comment by tombrennan06** [comment]
@jblindsay - thanks for responding. 

Yes, looks like that is the problem, as it runs successfully at the command line if the layername is omitted.

For already loaded (or temporary layers), QGIS automatically adds the layer name in the Processing Toolbox. So in order to run this via QGIS+plugin, the solution seems to be to save the layer to a Shapefile, and then select a file externally in the Processing Toolbox, rather than using a vector layer from within QGIS. 

This is possibly the same as #74

**Comment by alexbruy** [comment]
I can not reproduce this issue with the attached dataset. Either "Pour Points (Outlet)" is a vector or raster in both cases tool runs and produces result. Can you post exact steps to reproduce?

Also may I ask you to report plugin issues in the plugin bugtracker, not here. Thanks.

**Comment by tombrennan06** [comment]
Hi @alexbruy - I had originally thought this was a WhiteboxTools issue, not a plugin issue, which is why I had raised it here. However, as @jblindsay pointed out, the Watershed tool is simply not expecting a layername.

I'm still not clear if the issue is a plugin issue, or a QGIS issue. I've set out exact steps to reproduce below. If you think it's a plugin issue, I'm happy to raise in the plugin bugtracker.

Steps to reproduce my original problem (in QGIS):
1. Load the d8ptr.tif file (from the attached watershed.zip dataset)
2. Create a Temporary Layer named "output" in QGIS (Layer->Create Layer->New Temporary Scratch Layer... 
3. Add a point to the layer in QGIS (Add Point Feature), and Save Layer Edits, and Toggle Editing
4. Save the layer, or make the layer permanent (eg right-click on the "output" layer, Make Permanent, save to "output.shp")
5. Run the WhiteboxTools->Hydrological Analysis->Watershed tool in QGIS, with Input D8 Pointer File = "d8ptr", Input Pour Points Outlet file = "output"

This crashes with error: 
`"thread 'main' panicked at 'Unrecognized raster type', src\main.rs:72:21". `
The command line that is passed is:
`"C:\misc\WBT\whitebox_tools.exe" --run=Watershed --d8_pntr="E:\geodata\canyons\d8ptr.tif" --pour_pts="E:\geodata\canyons\outlet.shp|layername=outlet" --esri_pntr="False" --output="C:\Users\brennant\AppData\Local\Temp\processing_GbAMkk\f86161f3130e41378c94fd1954430adc\output.tif" -v`

However, if you load a points file ("output.shp") from outside into QGIS, rather than creating it inside QGIS during the same session, the command line passed is different:
` "C:\misc\WBT\whitebox_tools.exe" --run=Watershed --d8_pntr="E:\geodata\canyons\d8ptr.tif" --pour_pts="E:\geodata\canyons\outlet.shp" --esri_pntr="False" --output="C:\Users\brennant\AppData\Local\Temp\processing_GbAMkk\7d37816e6801409db9989d28467ebfc5\output.tif" -v`
This command line does not include the layername, and the tool runs successfully!

So the error only appears to arise when the points file is created and saved within QGIS, in the same session! 

I'm not clear if this is a QGIS issue or a plugin issue (or something else).

This can be worked around by creating the Pour Points layer in QGIS, saving the layer, removing the layer and then loading that layer again.

BTW thanks for the plugin @alexbruy !

**Comment by alexbruy** [comment]
@tombrennan06 small question just to make things clear. With your steps there are two layers called "output": one is memory layer created at the step 2 and another one is a file-based layer created from that memory layer at the step 4. Which one should be used? Also I think there is a typo somewhere, as in the log there is an "outlet.shp", not "output.shp".

From the log you have posted I assume that it should be file-based layer "output.shp" from the step 4, but want to double-check before looking for a fix.

**Comment by tombrennan06** [comment]
> @tombrennan06 small question just to make things clear. With your steps there are two layers called "output": one is memory layer created at the step 2 and another one is a file-based layer created from that memory layer at the step 4. Which one should be used? 

The one at step 4. Using the memory layer at step 2 does also cause an issue, but it's a different error. Using the Make Permanent command means that it's the same layer from QGIS's perspective. If you use Save As with the Add File to Map option, you do get two different layers

> Also I think there is a typo somewhere, as in the log there is an "outlet.shp", not "output.shp".

Sorry, yes - it was actually supposed to have been "outlet" in all cases. I have edited the post above. Hopefully that's not more confusing

> From the log you have posted I assume that it should be file-based layer "output.shp" from the step 4, but want to double-check before looking for a fix.

Yes, the file based layer after saving.

**Comment by Afrancioni** [comment]
It seems that @jblindsay pointed out a potential fix that was successful "I think the error is likely the result of this input parameter "**outlet.shp|layername=outlet**". The tool only wants a file name, which must be a shape file. The additional |layername=outlet will cause an unrecognized file type error."

In addition, this issue may be suited for the plugin issues for the plugin bug tracker maintained by @alexbruy. 

I am looking for more feedback on whether this issue has been resolved @tombrennan06. Looking to close this issue or move it to the plugin big tracker.

**Comment by alexbruy** [comment]
IMHO it can be closed, as this is not related to the WBT itself. I'm taking care of it.

**Comment by jblindsay** [comment]
Perfect, thanks @alexbruy.

**Comment by tombrennan06** [comment]
Thanks, yes. Not WBT - QGIS or plugin-related.
