### ISSUE TITLE
Development version of whitebox_tools (V1.5): Geomorphometric Analysis EmbankmentMapping

### ISSUE THREAD

**Issue by jacamofinane** [jblindsay/whitebox-tools#157]
Are vector polyline shapefiles (ESRI) enabled in the EmbankmentMapping tool?

The following command line code:
whitebox_tools -r=EmbankmentMapping --wd='C:/XX/Roadway_Embankment/' -i=Extract_Lidar.tif -o=Extract_Lidar_EMB.tif --road_vec=RoadCenteline.shp --search_dist=1.524 --min_road_width=7.3152 --typical_width=15.24 --max_height=2.1336 --max_width=26.0 --max_increment=0.5 --spillout_slope=4.0 --remove_embankments=False -v

throws the error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', whitebox-vector\src\shapefile\mod.rs:238:56

**Comment by jacobisleib** [comment]
I run into the same issue attempting to run BurnStreamsAtRoads.   I wondered if vector data must have the same extent as the input raster, which I then clipped and reran without success.  Now I suspect a shapefile formatting issue.  I have tried to run the WhiteboxTools CleanVector and ReinitializeAttributeTable tools to see if these would allow use of the vector data, again with no success.

**Comment by jacamofinane** [comment]
For my needs, turned out had to explicitly specify the shapefile path even though the path was a defined parameter in the command code. The raster data didn’t require full paths though.

Simple fix for my needs.

Joshua J Amos
Climate, Resilience, & Sustainability

***@***.***D75D51.3A465160]
Direct: 703.742.5968
Mobile: 301.639.9252

**Comment by jblindsay** [comment]
The vector doesn't need to have the same spatial extent, but it does need to have the exact same CRS. That is generally the case for all WBT tools. It cannot internally reproject data.

**Comment by jacobisleib** [comment]
Thank you both for clarification/input!  I was just able to successfully run the tool by specifying the complete path and filename for the road and stream parameters (these parameters do not seem to inherit the --wd path specified).  I did not need to specify the full path for the input and output, so same experience as Joshua.  Again, thanks both!

**Comment by jblindsay** [comment]
Excellent to hear @jacobisleib!
