### ISSUE TITLE
IdwInterpolation: error when exporting interpolation raster.

### ISSUE THREAD

**Issue by hudsonferreira** [jblindsay/whitebox-tools#159]
QGIS version: 3.16.4-Hannover
Qt version: 5.12.8
GDAL version: 3.2.1
GEOS version: 3.9.0-CAPI-1.16.2
PROJ version: Rel. 7.2.1, January 1st, 2021
Processing algorithm…
Algorithm 'IdwInterpolation' starting…
Input parameters:
{ 'base' : None, 'cell_size' : 15, 'field' : 'Cu__ppm_', 'input' : '/home/hudson_mra/Downloads/GEOQUIMICA AMBIENTAL/commondata/ornil/Geoquimica_sedimento.shp', 'min_points' : None, 'output' : '/home/hudson_mra/cu_ppm_idw.tif', 'radius' : 50, 'use_z' : False, 'weight' : 2 }

WhiteboxTools command:
"/home/hudson_mra/WBT/whitebox_tools" --run=IdwInterpolation --input="/home/hudson_mra/Downloads/GEOQUIMICA AMBIENTAL/commondata/ornil/Geoquimica_sedimento.shp" --use_z="False" --weight=2.0 --radius=50.0 --cell_size=15.0 --output="/home/hudson_mra/cu_ppm_idw.tif" -v
WhiteboxTools command output:
*******************************

* Welcome to IdwInterpolation *

*******************************

Reading data...

thread 'main' panicked at 'Attribute not found in table.', src/main.rs:72:21

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Execution completed in 0.04 seconds
Results:
{'output': <QgsProcessingOutputLayerDefinition {'sink':/home/hudson_mra/cu_ppm_idw.tif, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
**The following layers were not correctly generated**.
• /home/hudson_mra/cu_ppm_idw.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by Afrancioni** [comment]
Hello, 

It looks like there is an issue with the "Field" parameter in the IDWInterpolation Tool. WBT cannot find the "Cu__ppm_" attribute in the shape-file you specified. 

The "Field" parameter is case sensitive to what is located within the attribute table. My first thought would be to double check the spelling and any additional characters that may or may not be required. 

I also noticed the "Field" parameter is missing from the WhiteboxTools Command, which could also be causing the "thread 'main' panicked at 'Attribute not found in table" error. Are you able to run the tool outside of the QGIS environment? Using command line or through another front end such as wb_runner?

Regards,

**Comment by alexbruy** [comment]
This one not related to the WBT itself and should be closed. It is a bug in the QGIS provider, already fixed. In the future, please, report such issues in the right bugtracker.
