### ISSUE TITLE
Hypsometric Analysis tool won´t run without watershed file

### ISSUE THREAD

**Issue by monocilindro** [jblindsay/whitebox-tools#163]
Tested out in Windows 10 (binaries) and ArcGIS. Watershed file is said to be optional. The tool won´t run without it

**Comment by jblindsay** [comment]
@monocilindro I think this is an issue for the WBT ArcGIS front-end, as I can assure you that the back-end will run without a watershed file specified without any problem. Perhaps open the issue here: https://github.com/giswqs/WhiteboxTools-ArcGIS.
