### ISSUE TITLE
lidar_digital_surface_model AttributeError from Python

### ISSUE THREAD

**Issue by fluviotect** [jblindsay/whitebox-tools#164]
> AttributeError: 'WhiteboxTools' object has no attribute 'lidar_digital_surface_model'

Running in a notebook in Jupyter Lab using Python 3.7.3

Perhaps this is one of the commands that hasn't been ported to the Python API?

**Comment by giswqs** [comment]
Are you using the [whitebox](https://github.com/giswqs/whitebox-python) Python package? I can see the tool via Jupyter notebook.

![image](https://user-images.githubusercontent.com/5016453/121423228-0856e580-c93e-11eb-9ca1-9ce31cc83a69.png)

**Comment by jblindsay** [comment]
I can't say for the Jupyter notebook front-end, as I don't work with that, but I can say for sure that this tool is available from the Python API that I distribute WBT with. See [here](https://github.com/jblindsay/whitebox-tools/blob/05d9113544f6ac237493ffbf8fbf436e0d7de910/whitebox_tools.py#L6249).

**Comment by Afrancioni** [comment]
I believe this issue is resolved. @giswqs has provided a solution and the tool is currently listed/available within WhiteboxTools. I am going to close this issue but will re-open if it is not resolved.
