### ISSUE TITLE
isobasins: Last outlet id sometime one too big and miss last CSV connection 

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#172]
Sometimes, the last id skip one number like in the sequence 1, 2, 3, 4, 6 (no id 5) depending on the chosen size parameter. When it happens, it causes an other issue with the CSV connections file where the last id is missing. [This DEM can be used for testing](https://github.com/jblindsay/whitebox-tools/files/6919277/dem.zip).

**Using --size='30'**
`whitebox_tools.exe -r=Isobasins --dem='dem.flt' --output='isobasins_size30.flt' --size='30' --connections`
As expected, the call produces a raster with ids `1,2,3,4,5`  but the CSV misses one line for id 5:
| UPSTREAM | DOWNSTREAM | 
|----------|------------|
| 1 | 2 |
| 2 | 3 |
| 3 | N/A |
| 4 | 5 |

**Using --size='20'**
`whitebox_tools.exe -r=Isobasins --dem='dem.flt' --output='isobasins_size20.flt' --size='20' --connections`
This time, the call produces a raster with ids `1,2,3,4,5,7` (skips number 6 and uses 7 instead) and the CSV has one line per id, but id 6 is present in the upstream column and id 7 is present in the downstream colum:
| UPSTREAM | DOWNSTREAM | 
|----------|------------|
| 1 | 3 |
| 2 | 3 |
| 3 | 4 |
| 4 | N/A |
| 5 | 7 |
| 6 | N/A |

**Comment by jblindsay** [comment]
I have just committed a fix for this issue and am now closing.
