### ISSUE TITLE
trouble running Viewshed - thread 'main' panicked at 'index 43 out of range for slice of length 34'

### ISSUE THREAD

**Issue by Casyfill** [jblindsay/whitebox-tools#18]
thread 'main' panicked at 'index 43 out of range for slice of length 34', libcore/slice/mod.rs:1971:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

here is the tiff. 
https://www.dropbox.com/s/wyt545n5mpqpy1m/governer_island_ns2.tif?dl=0

Tried to fill None with zero - did not help the issue,

**Comment by jblindsay** [comment]
I'm not sure what you were using for your 'Viewing Station Vector File', so I just digitized a random point and ran the tool on your DEM. This is what I got, with no error:

<img width="728" alt="screen shot 2018-09-28 at 4 03 37 pm" src="https://user-images.githubusercontent.com/8441542/46231011-6121f380-c338-11e8-9c78-6b7a9a59c82b.png">

How did you set the viewing station?

**Comment by Casyfill** [comment]
Thanks - was playing with WhiteBox GAT and realized my stations were in Mercator; sorry for the hassle.

Side Q - it seems to take very long to compute those (running for one station for the third hour). I will definitely resample from 1m to at least 10, but wonder if there is a way to limit search in horizontal distance (or I probably can crop geotiff with buffer.envelope for each station, and then compose them).

**Comment by Casyfill** [comment]
and as a side q - perhaps it makes sense to either check for data consistency (e.g. stations are within DEM range / same projection) before the run? ` 'index 43 out of range for slice of length 34'` does not help much; don't know RUST but can PR on python interface (which might be a bad idea)

**Comment by jblindsay** [comment]
@Casyfill I'll certainly add a check to ensure that the input stations are within the footprint of the DEM. Not sure why it is taking so long to run on your computer, unless you are running it on a much larger DEM than what you posted here. The file you posted, with my arbitrary station location took 0.144261 sec to run on my machine. It was done faster than I could register. That said, if you have a large DEM and a lot of stations, it will certainly slow down a lot. After all, Viewshed operations are one of the most computationally expensive operations in the GIS field.

**Comment by Casyfill** [comment]
yeah, I am running it on the whole NYC now;  will crop  for each station then...

**Comment by jblindsay** [comment]
I just committed a change to Viewshed that issues an error if the station falls off the DEM extent and so I'm marking this as closed now. If you have other related issues, please let me know or open another issue.

**Comment by Casyfill** [comment]
thanks!
