### ISSUE TITLE
Typo `-toolbox` flag

### ISSUE THREAD

**Issue by brownag** [jblindsay/whitebox-tools#188]
Spotted this while reading through some of the argument parsing logic to try and understand a shell quoting edge case on Windows.

whitebox-tools-app/src/main.rs L209 should be `"-toolbox"` not `"-toolhelp"`
https://github.com/jblindsay/whitebox-tools/blob/ba0675f2daffbe88ec8875e4d7af60cb06373644/whitebox-tools-app/src/main.rs#L207-L211

```
$ whitebox_tools -toolbox
thread 'main' panicked at 'Unrecognized tool name -toolbox.', src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jblindsay** [comment]
Thanks for pointing this out. I just committed this change.
