### ISSUE TITLE
WBT v.2.0 binary issues

### ISSUE THREAD

**Issue by giswqs** [jblindsay/whitebox-tools#191]
It seems there are some issues with the v2.0 binaries downloaded from https://www.whiteboxgeo.com/download-whiteboxtools. The Windows binary is missing the `.exe` file extension. Adding the `.exe` file extension manually does not seem to work. The Linux version works fine, but the version number still shows v1.5.0.

**Windows:**
![](https://i.imgur.com/ukjJxhi.png)

**Linux**
![](https://i.imgur.com/cRipahc.png)

**Comment by giswqs** [comment]
The macOS version is also showing as v1.5.0

![](https://i.imgur.com/Xc6ZnfH.png)

**Comment by jblindsay** [comment]
Okay, we just updated the binaries to solve the versioning issue. That was just a matter of missing one place for reporting the version number (the cargo.toml file). Each of the binaries for the three supported platforms have been updated and you should find that resolved.

As for the exe extension on the Windows binaries, I'm not sure what to say. Rust has produced application files, I've tested them and they seem to work fine. As you know, I'm not a Windows user and so I am not that familiar with the platform. I assumed that it was just that trick where Windows sometimes doesn't show you the extension in a file name. But when I type './whitebox_tools.exe --version' in the command prompt, I get the expected result. I can also run the WB Runner application and running the Aspect tool on a file in there works without issue. All of this would indicate that the binaries work properly on Windows.

**Comment by alexbruy** [comment]
I am not familiar with cargo, but there are other TOML files with version number, e.g. in the modules folders like `whitebox_raster`. Maybe they should be updated too?

**Comment by jblindsay** [comment]
@alexbruy Good catch! I've updated those now, but they will have no impact on the version of the WhiteboxTools open-core application as reported in the issue. In fact, there is no reason why each of the sub-projects need to share a version number with the main WhiteboxTools application, but I will keep them in step for now.

**Comment by alexbruy** [comment]
> but they will have no impact on the version of the WhiteboxTools open-core application as reported in the issue

This was my assumption too, but I though I'd better mention these just in case they should be updated and match application version.

**Comment by jblindsay** [comment]
@alexbruy Yes, it's just the cargo.toml file in the main application that determines the version number printed out by whitebox_tools.exe at the command prompt and so we should be okay with the updated binaries that we uploaded earlier this morning. Thanks again for catching this issue though.

@giswqs We've now tested the Windows executables on two available (albeit ancient) Windows laptops and both worked fine with the files that we have. Are you still experiencing issues?

**Comment by giswqs** [comment]
@jblindsay Thanks for the quick fix. I can confirm that both the Windows and Linux versions are working now. It seems the link to download the macOS binary is broken https://www.whiteboxgeo.com/WBT_Darwin/WhiteboxTools_darwin_amd64.zip

**Comment by jblindsay** [comment]
@giswqs We have the link fixed now. We (on me) accidentally renamed the Mac binary, which broke the link, but we've named it back to the old 'WhiteboxTools_darwin_amd64.zip'. So, it looks like all of the issues raised here have now been resolved. I'm closing this issue and once again thank you both for spotting all these issues and for all your efforts.

**Comment by giswqs** [comment]
Thanks, John. I just tested the macOS binary. It works like a charm.

**Comment by acgold** [comment]
Hi @jblindsay, would it be possible to do an updated GitHub release that contains the updates from this thread? 

I am working on a Julia frontend [package](https://github.com/acgold/Whitebox.jl) for WhiteboxTools, and it uses an [automatic build](https://github.com/JuliaBinaryWrappers/WhiteboxTools_jll.jl) based on the latest GitHub release's `tar.gz` (v2.0.0 from August 30, 2021).  

I am seeing the same version behavior described above on my Mac, but otherwise works great!

```Julia
wbt.version()
WhiteboxTools v1.5.0 by Dr. John B. Lindsay (c) 2017-2021

WhiteboxTools is an advanced geospatial data analysis platform developed at
the University of Guelph's Geomorphometry and Hydrogeomatics Research 
Group (GHRG). See www.whiteboxgeo.com for more details.
```

**Comment by giswqs** [comment]
@acgold The WBT binaries are now hosted on [whiteboxgeo.com](https://www.whiteboxgeo.com/download-whiteboxtools/). They are no longer posted on GitHub. You can check out the [whitebox python package](https://github.com/giswqs/whitebox-python/blob/master/whitebox/download_wbt.py#L31) to see how to download the binaries through direct links when users install the package. If you use GitHub Actions to automatically download binaries from whiteboxgeo.com, it will likely fail. I had this issue with the Python and R frontend before and could not resolve it. The workaround is that you can use an older version of WBT for GitHub Actions, but when users install the frontend on their computer, the frontend downloads the latest binaries from whiteboxgeo.com.

**Comment by acgold** [comment]
Thanks for the info and example, @giswqs! I ended up being able to use the Julia community [build tree](https://github.com/JuliaPackaging/Yggdrasil/) to generate a build of v2.1.0 from the GitHub repo that can ship with the package.
