### ISSUE TITLE
wbt.conditional_evaluation() function return 0,but no result export

### ISSUE THREAD

**Issue by gaowudao** [jblindsay/whitebox-tools#197]
whitebox version: newest
Python version: python 3.8
Operating System: Mac
Description
Describe what you were trying to get done.
replace the rasterline values with DEM values

What I Did
wbt.conditional_evaluation(
i='/home/jovyan/data/mynotebook/data/rasterline.tif',
output='/home/jovyan/data/mynotebook/data/boundry.tif',
statement='value >= 0.0',
true='/home/jovyan/data/mynotebook/data/Elevation1.tif',
false='600.0')

when i used the whitebox.Runner()
got the following message:

./whitebox_tools --run="Conditionalevaluation" --wd="/Users/gaoxiang/Downloads/data" --input='/Users/gaoxiang/Downloads/data/rasterline.tif' --statement='value >= 0.0' --true='/Users/gaoxiang/Downloads/data/Elevation1.tif' --false=600.0 --output='/Users/gaoxiang/Downloads/data/boundry.tif' --compress_rasters

thread 'main' panicked at 'failed to execute process: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', whitebox-tools-app/src/tools/mod.rs:1258:26
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by jblindsay** [comment]
This looks like a file permission error. Do you have the file that you can share with me?

**Comment by gaowudao** [comment]
yeah, the Elevation1.tif and rasterline.tif can be download from here, https://github.com/gaowudao/pysheds/tree/master/data

**Comment by jblindsay** [comment]
I cannot replicate the error:
<img width="910" alt="Screen Shot 2021-09-25 at 11 11 15 AM" src="https://user-images.githubusercontent.com/8441542/134776320-35ba763b-0cce-4f87-9e0b-8cdd99d2a3e7.png">

The tool runs perfectly in the WhiteboxTools Runner for me. I think it is a system error on your side. Looks like you have a permission error. Perhaps it is how your WhiteboxTools is installed. I would recommend downloading the binary from the Whitebox Geospatial Inc. website, and then running the WhiteboxTools Runner using the [instructions in the user manual](https://www.whiteboxgeo.com/manual/wbt_book/whitebox_tools_runner.html).

**Comment by gaowudao** [comment]
ok  Thank you, I will reinstall Whiteboxtools Runner from the Whitebox Geospatial Inc.  Besides, another question is still unsolved.  

**What I Did: using whitebox-python**

wbt.conditional_evaluation(
i='/home/jovyan/data/mynotebook/data/rasterline.tif',
output='/home/jovyan/data/mynotebook/data/boundry.tif',
statement='value >= 0.0',
true='/home/jovyan/data/mynotebook/data/Elevation1.tif',
false='600.0')


**results**


return 0,but no result export

**Comment by gaowudao** [comment]
I solved the above problem with the binary from the Whitebox Geospatial Inc. Replaced the plugins files from python version with the plugins files in the binary

**Comment by jblindsay** [comment]
I suspect that this is a problem with the Python install of WBT, specifically the whitebox.Runner() command. But I don't believe it is a bug in the back-end and so I am closing this issue. I'm glad that you were able to work past it.

**Comment by geotom** [comment]
Having the same issue with a Python install. For me the raster_calculator results in the same failure and backtrace:

```
./whitebox_tools --run="RasterCalculator" --wd="/opt/project/utils/waterbodies/workspace/breached" --statement="raster1" --output='raster2'

thread 'main' panicked at 'failed to execute process: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', whitebox-tools-app/src/tools/mod.rs:1258:26
stack backtrace:
0:     0x5638694f19dc - std::backtrace_rs::backtrace::libunwind::trace::h7f0f727c679b121e
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
1:     0x5638694f19dc - std::backtrace_rs::backtrace::trace_unsynchronized::h27b8207adc787597
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:     0x5638694f19dc - std::sys_common::backtrace::_print_fmt::h18c4a15687f3f453
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
3:     0x5638694f19dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7077f94cc0b2a619
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
4:     0x56386952fdaf - core::fmt::write::hd1fcbdc89ccede50
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1096:17
5:     0x5638694f11e6 - std::io::Write::write_fmt::h3030f95a96ab63e0
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/io/mod.rs:1568:15
6:     0x563869506365 - std::sys_common::backtrace::_print::hce920b6e4ede72f2
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:49:5
7:     0x563869506365 - std::sys_common::backtrace::print::h63694f3a744810f6
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:36:9
8:     0x563869506365 - std::panicking::default_hook::{{closure}}::h2f22ad38e825d5e1
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:208:50
9:     0x563869505f33 - std::panicking::default_hook::hc0998dccd7f968a3
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:225:9
10:     0x563869506995 - std::panicking::rust_panic_with_hook::h618d5ded1dbe5ea3
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:591:17
11:     0x5638694f21f7 - std::panicking::begin_panic_handler::{{closure}}::h64f3a351a9df3931
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:497:13
12:     0x5638694f1b3c - std::sys_common::backtrace::__rust_end_short_backtrace::hf7a8c7450479e920
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:141:18
13:     0x563869506542 - rust_begin_unwind
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:493:5
14:     0x56386952fae1 - core::panicking::panic_fmt::hac8d59bba791921f
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/panicking.rs:92:14
15:     0x56386952b583 - core::result::unwrap_failed::h386947b3c6c45634
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/result.rs:1284:5
16:     0x563868c35345 - whitebox_tools::tools::ToolManager::run_tool::h324febd58ab9a2e8
17:     0x563868906abf - whitebox_tools::run::hf0adb91db1a610a3
18:     0x563868903e2a - whitebox_tools::main::h48bb4032c3c51024
19:     0x5638691096f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9669996f076d0ae7
20:     0x5638686f4dc9 - std::rt::lang_start::{{closure}}::h4d629acb5d2e5dbf
21:     0x563869506d4a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hacf21ab16c4aa1f7
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/core/src/ops/function.rs:259:13
22:     0x563869506d4a - std::panicking::try::do_call::h002bd74c4d814788
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:379:40
23:     0x563869506d4a - std::panicking::try::hae0844c0aa736d3d
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panicking.rs:343:19
24:     0x563869506d4a - std::panic::catch_unwind::hec4fe4ae39575e8f
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/panic.rs:431:14
25:     0x563869506d4a - std::rt::lang_start_internal::h024664467cde3297
at /build/rustc-h1hlaa/rustc-1.51.0+dfsg1+llvm/library/std/src/rt.rs:51:25
26:     0x563868907f02 - main
27:     0x7f4f46d5d0b3 - __libc_start_main
28:     0x5638686f4cda - _start
29:                0x0 - <unknown>
```

**Comment by MarcusChMa** [comment]
I do encounter the exact same error using Whitebox Python frontend from the `whitebox `package. Running the tools locally, from the runner, or QGIS, all work fine. But ConditionalEvaluation hangs on this permission error using Python. It is the only tool so far that fails this way. All other tools work fine in the same folder, with the same permissions in my system.

```
import whitebox
wbt = whitebox.WhiteboxTools()

wbt.conditional_evaluation(
    i = "/path/to/raster/input.tif",
    output = "/path/to/raster/output.tif",
    statement = "'value >= 3'",
    true = 1,
    false = None
)
```

**Comment by giswqs** [comment]
This appears to be the whitebox frontend issue. Please open an issue at https://github.com/giswqs/whitebox-python
