### ISSUE TITLE
Documentation for raster_calculator

### ISSUE THREAD

**Issue by mgironamata** [jblindsay/whitebox-tools#201]
whitebox version: 2.0.0
Python version: 3.6
Operating System: Windows 10

Description

The documentation for the raster_calculator function does not seem to be correct. It currently reads: "This tool performs a conditional evaluaton (if-then-else) operation on a raster", which is the documentation for the conditional_evaluation tool. This is a very small issue but I thought I would raise it because it has an easy fix.

**Comment by jblindsay** [comment]
It seems correct to me: https://www.whiteboxgeo.com/manual/wbt_book/available_tools/mathand_stats_tools.html#RasterCalculator

**Comment by jblindsay** [comment]
Ultimately, all of the documentation for WBT is drawn from the comments associated with each tool's source code, and as you can see, it is correct there as well:

https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-plugins/src/raster_calculator/main.rs

**Comment by mgironamata** [comment]
Thanks. I should have clarified I am specifically referring to the documentation of the raster_calculator function in the Python helper file (whitebox_tools.py): https://github.com/jblindsay/whitebox-tools/blob/master/whitebox_tools.py#L8247

This issue was initially raised in the whitebox-python repository: https://github.com/giswqs/whitebox-python/issues/33

**Comment by jblindsay** [comment]
Yes indeed, well spotted! I've just uploaded the fix. Thanks for reporting the issue.

**Comment by cefect** [comment]
I think there is still an issue with the RasterCalculator documentation [here](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/mathand_stats_tools.html?highlight=RasterCalculator#rastercalculator):
![image](https://user-images.githubusercontent.com/47092034/206879398-430675b1-74a2-4f6f-9410-1ea044969caa.png)

Also, the provided source code link is broken.
