### ISSUE TITLE
Problem with creating an hydrologic enforced DEM with WBT

### ISSUE THREAD

**Issue by geotom** [jblindsay/whitebox-tools#207]
Hello,

I am posting this here as a general question, not a bug report. I have found only the Google groups but could not create a conversation there. Please let me know if there is a better place for posting my question. Then as well thank you for your previous quick responses and in general for all the work on WBT. I really appreciated this sophisticated toolbox.

My problem. I have a workflow to create a hydrologic enforced DEM (From a SRTM DEM) that has the following steps:

![2021-11-23_22-26-09](https://user-images.githubusercontent.com/5240363/143132404-37032e3c-ea5e-48ba-866d-6e23b44184f0.png)

The sequence is to first apply a filter to the SRTM DEM to smoothen it, then I remove single cell pits and afterwards use either the `breach_depressions ` or `fill_depressions` tools to fill remaining depressions in my DEM. I optionally burn streams from OSM in my prepared DEM and then create a D8 pointer grid (`d8_pointer`) and then try to delineate for instance the streams based on it.

My study area is in the Swiss alps, so I have a pretty well defined orographic situation with streams from the hillslopes and a confluence in the valleys. Unfortunately I am struggling to get a proper result that reflects this situation. In the following image one can see that the delineated streams from hillslopes follow downhill, but never join in the valley (Blue = OSM stream).

![2021-11-23_22-42-54](https://user-images.githubusercontent.com/5240363/143134424-089dfad9-c45c-4a26-9024-427be7694f28.png)

The reason is a DEM with no clear flow direction in the valleys due to man small depression patches in my DEM, which I thought to get rid of with either the breaching or the filling tools. Both do not result in a DEM from which I can generate a proper d8 pointer grid.

I'm using the filling tool for instance with no max depth parameter, so I would expect the depressions in my valley floors getting filled. Any input is appreciated. Am I am doing something wrong here? Maybe my approach is flawed or I use the wrong sequence of DEM preparations?

**Comment by Afrancioni** [comment]
This post was addressed within the Google Group. Please see the following link for more information (https://groups.google.com/u/1/g/whiteboxtools/c/BqmKG8LsMjM).
