### ISSUE TITLE
Problem running NewRasterFromBase on Windows

### ISSUE THREAD

**Issue by AlisterH** [jblindsay/whitebox-tools#21]
Having identified several issues with the input parameters that can cause problems on Windows (#20), and also realised that --input is not actually the right parameter, I'm still unable to get NewRasterFromBase to run on Windows:
````
C:\Processing>whitebox_tools.exe --version
whitebox-tools v0.11.0 by Dr. John B. Lindsay (c) 2017-2018

C:\Processing>whitebox_tools.exe --run=NewRasterFromBase --wd="C:\Processing\" -i="simple.tif" --output="simple57.tif" --value=nodata --data_type=integer
thread 'main' panicked at 'Tool run with no paramters.', src\main.rs:76:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
````
I do not believe the input file is the problem - it works with the Linux whitebox_tools, and I have tried a variety of files, all failing.

Is there anything else obvious I'm missing?  Maybe it is just an issue with the order in which I've specified the parameters - there is probably some combination I haven't tried.
Would a proper debug build for Windows help?

**Comment by jblindsay** [comment]
Hi @AlisterH. I've been trying to track this one down for a while and I can't seem to replicate. I see that you have been using WhiteboxTools from the command line. Are you able to run NewRasterFromBase when you run it from WhiteboxTools Runner or calling it from a Python script? I'm wondering if its an issue with the terminal application specifically. It seems to run fine on my terminal.
