### ISSUE TITLE
JensonSnapPourPoints Failed to Fill Whole Buffer and ShapeType error in Python and CMD

### ISSUE THREAD

**Issue by Stillelk** [jblindsay/whitebox-tools#211]
Using Python:
wbt.jenson_snap_pour_points
(r"D:\Exclude\Fire_Severity\WatershedNHD\XXXX_XXXXWQ40A.shp", 
  r"D:\Exclude\Fire_Severity\WatershedNHD\NHD_StreamNet.tif", 
  r"D:\Exclude\Fire_Severity\WatershedNHD\XXXX_XXXXWQ40A_PourPoint.shp", 100)

and am receiving the following error:
thread 'main' panicked at 'failed to fill whole buffer', whitebox-tools-app\src\main.rs:72:21

I also receive the same 'failed to fill whole buffer' error when running the Watershed tool on a set of data built entirely in Whitebox, the above error is from clipped data from the National Hydrologic Dataset. 
I have tried different snap distances and I have tried to run it in the command line. I have also tried with a shapefile of multiple pour point, I have 23 total, and receive an error of:

thread 'main' panicked at 'Unrecognized ShapeType: 33554432', whitebox-vector\src\

Shapefiles were created in ArcGIS Pro 2.8.3 and a second set were created in ArcMap 10.8 as a test.  The stream raster covers approximately 50 square miles. 

I am new to Whitebox tools and I am sure I am just missing something obvious.  Any help would be great.

**Comment by jblindsay** [comment]
"'main' panicked at 'failed to fill whole buffer" sounds like an out-of-memory error. How large is that NHD_StreamNet.tif file and how much memory does your computer have?

**Comment by Stillelk** [comment]
NHD tif is 63 MB on a Win 10 Enterprise, 64 gb of ram, I9 laptop. Second test was with a 257 MB tif on a Win 10 Pro, 32 gb of ram, I7 desktop. NHD data is from clipped from National Hydrology Dataset and projected to NAD83 2011 UTM. 
Second test, all rasters were in same coordinate system, but everything was built in Whitebox from a DEM from USGS 3DEP. Whitebox stream network is 32 bit floating point (257mb), NHD is 8 bit unsigned char(63mb).
I will try clipping my rasters down and see if that makes a difference.

**Comment by jblindsay** [comment]
That doesn't sound particularly large actually. It sounds like something else may be going on. Would you mind sharing your data with me?

**Comment by Stillelk** [comment]
[HydroTest.zip](https://github.com/jblindsay/whitebox-tools/files/7697634/HydroTest.zip)
[HydroTest2.zip](https://github.com/jblindsay/whitebox-tools/files/7697635/HydroTest2.zip)
HydroTest is clipped NHD data, HydroTest2 was built in Whitebox. HydroTest from enterprise license ArcGIS Pro 2.8.3, HydroTest2 from home use license ArGIS Pro 2.9.
Thanks for the help with this.

**Comment by jblindsay** [comment]
Thank you for sending the data along. With this data in hand, I was able to diagnose the issue, which was related to a bug in my Shapefile reader, specifically within the code for reading files of the PointZ ShapeType. I have committed the fix to the repository. It will be part of the next public release of WBT, but if you cannot wait until then, I would suggest either compiling from source or changing your pour points vector file to a plain Point ShapeType rather than a PointZ. Thanks for reporting the error and providing enough information to help me find the bug. I'm closing this now, but if you continue to experience the issue, please feel free to re-open.
