### ISSUE TITLE
BurnStreamsAtRoads - `--roads` does not use `--wd`

### ISSUE THREAD

**Issue by brownag** [jblindsay/whitebox-tools#214]
It appears that the BurnStreamsAtRoads tool does not use `--wd` / `working_directory` for `--roads`.

This command errors:
```
$ whitebox_tools.exe --run=BurnStreamsAtRoads --dem=dem.tif --streams=streams.shp --roads=streets.shp --width=270 --output=burn.tif -v --wd=E:/temp
*********************************
* Welcome to BurnStreamsAtRoads *
*********************************
Reading streams and roads data...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\vector\shapefile\mod.rs:238:56
stack backtrace:
```

Whereas this works as expected:

```
whitebox_tools --run=BurnStreamsAtRoads --dem=dem.tif --streams=streams.shp --roads=E:/temp/streets.shp --width=270 --output=burn.tif --wd=E:/temp
```

https://github.com/jblindsay/whitebox-tools/blob/6c41158d8464636ae6c4860a121308bf4f429e72/whitebox-tools-app/src/tools/hydro_analysis/burn_streams_at_roads.rs#L238-L258

I think following lines are missing:

```rust
 if !roads_file.contains(&sep) && !roads_file.contains("/") { 
     roads_file= format!("{}{}", working_directory, roads_file); 
 } 
```

**Comment by jblindsay** [comment]
I've just added code to append the working directory to the roads file if unspecified. This fix should resolve your issue and will be available in the upcoming v 2.1 release.
