### ISSUE TITLE
LidarIdwInterpolation multiple inputs

### ISSUE THREAD

**Issue by ldbuma** [jblindsay/whitebox-tools#215]
Is there a way to have multiple defined las files as input for the LidarIdwInterpolation tool? I've tried several options to have 2 files as input, but can't get it working. When I use only 1 as input it does work.

I would like to use 1 big main las file as input and add another one with only corner points (offsetted) of the theoretical lidar box to force the corner of the pixels of the output at coordinates that are dividable by the grid cell size, as this doesn't seem to be a standard in LidarIdwInterpolation of WBT.

**Comment by jblindsay** [comment]
The user manual states, 

> "The user must specify the grid resolution of the output raster (--resolution), and optionally, the name of the input LiDAR file (--input) and output raster (--output). Note that if an input LiDAR file (--input) is not specified by the user, the tool will search for all valid LiDAR (*.las, *.zlidar) contained within the current working directory. This feature can be very useful when you need to interpolate a DEM for a large number of LiDAR files. Not only does this batch processing mode enable the tool to run in a more optimized parallel manner, but it will also allow the tool to include a small buffer of points extending into adjacent tiles when interpolating an individual file. This can significantly reduce edge-effects when the output tiles are later mosaicked together. When run in this batch mode, the output file (--output) also need not be specified; the tool will instead create an output file with the same name as each input LiDAR file, but with the .tif extension. This can provide a very efficient means for processing extremely large LiDAR data sets."

So to put it simply, all you need to do is to locate all the LiDAR files that you want to interpolate within a single directory, then set the working directory for WBT and run the tool without specifying either the input or output file parameters. It will then interpolate all of the files contained within the working directory. All of the LiDAR tools operate in this same batch mode.
