### ISSUE TITLE
Memory limitations

### ISSUE THREAD

**Issue by InsolublePancake** [jblindsay/whitebox-tools#216]
First off, I know that this is mentioned in the known issues. But I wasn't sure that the limitation was so big as it appears to be in my case. I have developed a workflow that uses whitebox tools to extract drainage lines from a DEM. It is admirably fast on the test data, but the memory usage means that we can't process what I would consider a moderately sized 2 GB DEM. We are running on a machine with 96 GB of RAM. This is far from our largest DEM - we have a 6 GB one that we would like to process soon.

I'm raising this issue to check firstly whether this seems about right to you - should a 2 GB DEM require >96 GB of RAM to run raster processing tools? (if not, possibly we are doing something wrong in implementation). And if that is correct, do you know of anyone who has managed to get around these issues somehow? I've considered breaking the DEM into chunks, but that wouldn't make sense when it came to the flow accumulation stage.

Any help you can provide would be greatly appreciated. Whitebox tools seems like a fantastic resource and it would be a huge bonus to my work if I could use them on larger datasets.

**Comment by jblindsay** [comment]
You have not provided nearly enough information here for me to respond in a helpful way. What tool are you trying to use? What error message did you receive? What is the size of the DEM in terms of rows and columns?

**Comment by InsolublePancake** [comment]
Hello, sorry about that. I will elaborate. I'm accessing the tools through the Python api.
I initially tried running fill_depressions with the 2 GB DEM on a machine with 60 GB of RAM. This fell over with the following message:

2021-12-09 16:20:43,220 drainage_lines@562:default_callback 207712 [DEBUG] Reading data...
2021-12-09 16:22:48,834 drainage_lines@562:default_callback 207712 [DEBUG] memory allocation of 45045269632 bytes failed

I don't know much about memory allocation, I assume that the system isn't able to allocate all of it's RAM to the process and that's why it fails to allocate 45 GB on a machine with 60 GB RAM.

I managed to run the same DEM on a machine with 96 GB of RAM and it completed without error. I then tried to create a D8 pointer dataset with the corrected DEM and this fell over with a similar memory allocation error to above. I didn't make note of the number of bytes.

The commands for these two tools were:

./whitebox_tools --run="FillDepressions" --dem='/data/DTM.tif' --output='/data/fixed_dem.tif' --fix_flats --max_depth='1' --compress_rasters

./whitebox_tools --run="D8Pointer" --dem='/data/fixed_dem.tif' --output='/data/D8_pointer.tif' --compress_rasters

Please let me know if you need any more information.
Thanks

**Comment by jblindsay** [comment]
I still need to know how many rows and columns your raster is. The size of it on disc (2 GB) does not mean very much to me, since it is likely stored in a compressed file format.

**Comment by jblindsay** [comment]
I can tell you that the maximum memory usage of the D8Pointer tool should be about 16 bytes per pixel. It reads in the entire raster DEM (at 8 bytes per pixel) and it also holds in memory the output raster (also at 8 bytes per pixel). The actual memory usage may vary a little based on the system, but that should be a general guide to how much memory this tool requires. The FillDepressions tool likely has a higher per-pixel memory usage than the D8Pointer tool.

**Comment by InsolublePancake** [comment]
Ah yes, it's 51152 x 110077

**Comment by jblindsay** [comment]
Okay, so if I'm doing my math correct, that means that the tool would require about 90 GB of memory to process that DEM with the D8Pointer tool. As you say, it's unlikely that one process is allowed to allocate that percentage of your total RAM, and of course there needs to be enough left-over to handle the OS and other open processes. You're 2 GB DEM is really more likely a 22 GB DEM that has has a lot of compression. I have certainly processed 2 GB sized DEMs in WBT many times in the past, but 22 GB would be among the largest that I have ever tried to process.

**Comment by jblindsay** [comment]
My guess is that your DEM contains a lot of NoData values around the edges, that account for that large compression ratio. NoData values may be no-data, but they are still data in memory, even if they have different signally for tool processing.

**Comment by InsolublePancake** [comment]
Thanks for getting back to me. Sorry for the slow replies on my part.
Do you know of anyway around these issues? Others must have come up against this limitation before.

**Comment by jblindsay** [comment]
You said from the start that WBT was "admirably fast on the test data." The reason for this characteristic is the design that I have taken in developing the project. There are many reasons why it's so fast: I have parallelized most operations that can be easily parallelized, I have developed it using a very performant and modern programming language (Rust), and I have developed the code to work with raster data all the way down the stack, even in the way that rasters are read and written to file. Importantly, **memory requirements and speed are orthogonal design goals**. At the time that I started this project, it seemed that computer systems with considerably larger amounts of memory were just around the corner, and so I decided to design WBT to favour speed over memory. It's hard to get around that compromise. Ultimately your options are 1) try to cut your raster DEM into smaller pieces that you can work with, 2) use a system with more memory, or 3) use an alternative software that has been developed with different design goals that favour memory usage over speed. Most WBT users are not trying to process 22 GB DEMs. It's true that some, like yourself, probably do have need to process such large files and you will always find that you are up against the wall of compromises that I've outlined above.

**Comment by InsolublePancake** [comment]
Ok, thanks so much for taking the time to answer my questions. I will try to get it work by chunking the regions and recombining later. It's a fantastic set of tools you've developed here, it is much appreciated!

**Comment by geotom** [comment]
We have an issue that might be related to this in the FlowAccumulationFullWorkflow.
This module simply exists gracefully without any error messages after writing the DEM file (around line https://github.com/jblindsay/whitebox-tools/blob/59d345138f86a50602182a2dd5b0a410449f6511/whitebox-tools-app/src/tools/hydro_analysis/flow_accum_full_workflow.rs#L613). We assume this is a memory issue as well as our DEM is 20527x9187 and executed within a docker container.

What improvements were made to this? I think I read about a batched approach @jblindsay? How did you solve your issues in the end @InsolublePancake ?

**Comment by InsolublePancake** [comment]
Hi @geotom, unfortunately we've not solved the issue of handling large basins. Our current approach is to downsample the DEM to a very coarse resolution, then run the basins tool to get the rough location of the basins and break up the DEM accordingly. However, for very large basins there is still a limit. We want drainage lines and catchments for the Mississippi and the Amazon basin and for this I think we're going to have to use cloud processing.

**Comment by geotom** [comment]
Thank you for your feedback @InsolublePancake!
We use the FlowAccumulationFullWorkflow (See my issue: https://github.com/jblindsay/whitebox-tools/issues/401), so I wonder if your approach would be feasible with your approach (?) as the FlowAccumulationFullWorkflow calculates the flow direction and accumulation all in one tool/step. We would probably need to switch to the individual tools to implement your approach.

**Comment by InsolublePancake** [comment]
@geotom running the tools separately might help, although I imagine the individual tools are run consecutively within the workflow, so perhaps it won't.
However, I've not actually used the whiteboxworkflows because my work are wary of the freeware license, which seems to require that individual users register with whitebox.

**Comment by jblindsay** [comment]
Just to clarify, Whitebox Workflow's freeware license does not require individuals to register with Whitebox Geospatial. You can use WbW without any restrictions or requirements. The only reason that we have distributed WbW as freeware rather than open source, like WhiteboxTools' OS license, is because the codebase for Whitebox Workflows Professional (WbW-Pro) is actually embedded in the same codebase for WbW. This makes it makes it much simpler to install, use, and maintain.

**Comment by geotom** [comment]
Thank you @InsolublePancake and @jblindsay for the clarification.
So far we are using WbW in its freeware version and are quite happy with it. Nevertheless the memory consumption for flow direction/accumulation (See #401) could be a showstopper for us. I understand that great work costs. As an alternative to the proposed solution (splitting DEM in basins) is there maybe a technical solution to bring the memory consumption down or make the algorithm adopt to memory limited environments or very large DEMs without just exiting without an error? Is there maybe a way to fund specific improvements @jblindsay beside the normal licenses?
