### ISSUE TITLE
How to Use a List as an input to sum_overlay command

### ISSUE THREAD

**Issue by bhegman** [jblindsay/whitebox-tools#218]
Hi.  I have 100 rasters that I'm trying to sum together.  I generated a list with the os.listdir command but the Whitebox tool sum_overlay doesn't seem to like the format of the list. 
 
The list is like this ['cost_pathway_1.tif', 'cost_pathway_2.tif', 'cost_pathway_3.tif'] 
but Whitebox wants this 'cost_pathway_1.tif';cost_pathway_2.tif';cost_pathway_3.tif'

Do I just need to reformat the list with python or is there any way that Whitebox will read the list as is?

In my example, I hard coded three of the inputs so I know it works this way, but I would like to pass the list which is called cost_pathway_files.

Thanks in advance.

Here's my code:  

# import tools from WBT module

from WBT.whitebox_tools import WhiteboxTools
import os
# declare a name for the tools

wbt = WhiteboxTools()

# Set the Whitebox working directory
# You will need to change this to your local path name
# set the output folder if different
out_dir = "D:/Permeability_model/Hinesburg"
wbt.work_dir = "C:/Users/whegman/OneDrive - Middlebury College/White_Box/testData"

# define an output file name
cost_pathway_summed = os.path.join(out_dir,f'cost_pathway_summed.tif')
# to find all files that are cost_pathway_....tif we will use os package
all_output_files = os.listdir(out_dir)
cost_pathway_files = [file for file in all_output_files if "cost_pathway_" in file and file.endswith('.tif')]
print (cost_pathway_files)

# run the sum_overlay tool to combine all 100 cost pathway rasters
wbt.work_dir = out_dir
wbt.sum_overlay(
    'cost_pathway_1.tif;cost_pathway_2.tif;cost_pathway_3.tif',
    cost_pathway_summed
)

**Comment by giswqs** [comment]
You can use “;”.join(cost_pathway_files) to convert the list to a string.
