### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Robinlovelace** [jblindsay/whitebox-tools#22]
It would be useful to have a docker image of this, so you could pull-down and run a version of `whitebox-tools` in environments that lack rust (typed from a Windowz desktop that has docker but no admin rights let alone a rust compiler). Happy to help with this if I get the 👍

**Comment by giswqs** [comment]
Are you trying to test the functionality of the tools or compile the tools? For testing the tools, you can try the WhiteboxTools command-line program or the [whitebox Python package](https://github.com/giswqs/whitebox), which is built on WhiteboxTools. Check the links below for a  whitebox tutorial that runs on an interactive binder environment. For compling the tools using Rust, I can also help setup a docker image to be run on the binder environment. This [EvCxR Jupyter Kernel](https://github.com/google/evcxr/tree/master/evcxr_jupyter) seems helpful.   

HTML version: https://gishub.org/whitebox-html
Interactive Notebook: https://gishub.org/whitebox-cloud

**Comment by Robinlovelace** [comment]
I can compile and use the tools on my Ubuntu set-up no problem. It's just that it's not easy to use them from an environment that lacks rust or the ability to execute new programs. I think your Jupyter notebook suggestion is a good one: that way you can have the notebook running as an interactive session inside a browser pointing at a localhost port - I use this approach freqently with RStudio Server. I think a 'barebones' command line tool would also be useful though, perhaps one that works as follows ([source](https://docs.docker.com/engine/reference/commandline/exec/)):

```
docker exec whitebox-docker ./whitebox_tools --wd='/Users/johnlindsay/Documents/data/' --run=DevFromMeanElev
```
--input='DEM clipped.dep' --output='DEV raster.dep' -v

**Comment by giswqs** [comment]
I have created a [Dockerfile](https://github.com/giswqs/whitebox-rust-binder/blob/master/binder/Dockerfile) for WhiteboxTools and deployed it to [Binder](https://mybinder.org/v2/gh/giswqs/whitebox-rust-binder/master). Now you can simply use an Internet browser to run Rust code and complie WhiteboxTools on the cloud. It takes ~17 minutes to complie on Binder while it only takes ~2 minutes on my local Linux computer. 

GitHub repo: https://github.com/giswqs/whitebox-rust-binder
Example: https://github.com/giswqs/whitebox-rust-binder/blob/master/examples/whitebox-rust.ipynb

![](https://i.imgur.com/u87HxF4.gif)

**Comment by jblindsay** [comment]
I'm always amazed when I see the different environments that people are deploying WhiteboxTools into. @giswqs Thanks for taking the time to create this docker deployment. @Robinlovelace As I think you know, I am a MacOS user and that tends to be the environment that I develop and test WhiteboxTools in. I do compile the code on Linux to create the compiled binary for distribution. Can you explain to me why this compiled binary is difficult for linux users to use without Rust installed on their machines? Are they not able to simply call this exe? Is it a matter of system privileges? What is the best linux-specific method of distributing WhiteboxTools?

**Comment by Robinlovelace** [comment]
Hi @jblindsay thanks for the response. I didn't know about those binaries, that's fantastic! The issue on my work desktop is I don't have admin rights but do have docker (strange I know!) which may be quite a specific case. However I still think there are advantages of dockerisation. If you can create a minimal image that auto-deploys, people will have instant docker access to the latest version. Apart from testing benefits of using up-to-date and auto-deployed code without having to compile locally (which is what I tend to do on Linux), this would make WhiteboxTools more accessible generally (going back to your concept of 'open access software').

**Comment by jblindsay** [comment]
Alexander Bruy also kindly committed a Docker recipe for WhiteboxTools. Instructions are now in the README. Thanks Alex!
