### ISSUE TITLE
AttributeError: 'WhiteboxTools' object has no attribute 'geomorphons'

### ISSUE THREAD

**Issue by cflynn8** [jblindsay/whitebox-tools#223]
I am trying to run the goemorphons tool in python with whitebox. Numerous other tools are working fine. 

When I run this code:
geom_output = geom_path+"\\"+raster_root_name+"_Geom.tif"
wbt.geomorphons(sm_dem_output,
                geom_output,
                search = 6,
                threshold = 2,
                tdist = 1,
                forms = True)

I get this error:
AttributeError: 'WhiteboxTools' object has no attribute 'geomorphons'

I am using version 2.0.0.

**Comment by jblindsay** [comment]
Geomorphons is in the development branch of WBT and will be part of the v2.1 release, which should sometime happen in the next couple of weeks. We are just preparing for that release now. If you can't wait for it, feel free to compile from source, and you should find that the tool is there and available.

**Comment by cflynn8** [comment]
Excellent, thank you!

**Comment by jblindsay** [comment]
No problem.

**Comment by rengifoortega** [comment]
Hi guys, 
first, a great thanks for implementing geomorphons in WTB.  You have improved greatly the speed of calculation.  300 min in  GRASS  GIS vs. 26 min  WTB (1 meter DEM with Total Cells:  1824000000), but  I'm wondering about the parameters implemented. Originally geomorphons consist of Search, skip, flat and dist (see image attached). But you seem to have implemented only Search, flat, and dist, but not skip. I am struggling to get the same results as in GRASS GIS, where I can control the extent of the flat areas.

I also found some  differences in the python fuction parameters and  the command line parameters. I they supposed to be different?.
![2022-02-10 09_58_05-Geomorphometric analysis - WhiteboxTools User Manual](https://user-images.githubusercontent.com/98947748/153376144-ca2fa242-d6f0-4788-b917-c14e75f3b220.png)

Thanks a lot, once more. Great work!
best regards
Rengifo Ortega
