### ISSUE TITLE
QGIS Processing Plugin -- not available

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#238]
As I'm sure you know Alex Bruy's website and wbt processing plugin has been shut down. 
![image](https://user-images.githubusercontent.com/47092034/160387647-0c3e57ca-dfb6-47ea-892c-02b01143f869.png)

So the [instructions](https://www.whiteboxgeo.com/manual/wbt_book/qgis_plugin.html) on the wbt homepage no longer work. Is there a place we can access an archive of his most recent version?  

Apologies if this isn't the best place to post such issues.

**Comment by Afrancioni** [comment]
Please refer to the GoogleGroup discussion post (https://groups.google.com/u/1/g/whiteboxtools/c/lnRS9nAft94). In this link there is a solution to download and install the QGIS plugin from source. Additionally, you can use WhiteboxTools from many other front ends such as WhiteboxRunner, ArcGIS, Jupyter and more. You can also interact with WBT through our python API or R studio.
