### ISSUE TITLE
cartographic depth-to-water index

### ISSUE THREAD

**Issue by wiesehahn** [jblindsay/whitebox-tools#246]
Are there any thoughts about implementing the cartographic depth-to-water algorithm?

**Comment by jblindsay** [comment]
I just added the [cartographic depth-to-water index](https://whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#depthtowater) to the WhiteboxTools [General Toolset Extension](https://www.whiteboxgeo.com/whitebox-general-toolset/) (GTE).

**Comment by wiesehahn** [comment]
Thanks for your super quick implementation (although I don't own GTE :))
