### ISSUE TITLE
Inconsistence in the help URLs

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-tools#25]
I noticed small inconsistence in the manual URL's. Looks like for the wast majority of tools group name in the URL constructed by replacing spaces with underscores and converting text to the lower case, e.g.`LiDAR Tools` -> `lidar_tools`. But for `Math and Stats Tools` this is not the case, this group converted to `mathand_stats_tools`. Is this intentional or there is a minor bug in the URL construction?

Asking because in the WhiteboxTools QGIS plugin I create help links automaticaly using tool name and group and this inconsistence does not allow to generate valid urls for tools from the Math as Stats group. May I ask for some information how help URLs are generated, are my assumptions correct?

**Comment by giswqs** [comment]
I encountered the same issue when trying to generate URLs of source code and user manual for [WhiteboxTools-ArcGIS](https://github.com/giswqs/WhiteboxTools-ArcGIS). I noticed the slight URL differences in group names between [source code](https://github.com/jblindsay/whitebox-tools/tree/master/src/tools) and [user manual](https://jblindsay.github.io/wbt_book/available_tools/index.html). As a result, I created two different dictionaries for group names and used `wbt.view_code(tool_name)` to return URLs.  

Source code group vs User manual group:
- terrain_analysis vs geomorphometric_analysis
- hydro_analysis vs hydrological_analysis
- lidar_analysis vs lidar_tools
- image_analysis vs image_processing_tools
- math_stat_analysis vs mathand_stats_tools

[WhiteboxTools-ArcGIS/WBT/PRE/automation.py](https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WBT/PRE/automation.py#L319
)
```
import whitebox
wbt = whitebox.WhiteboxTools()

## Read from whitebox_tools.py
github_cls = {
    "Data Tools": "data_tools",
    "GIS Analysis": "gis_analysis",
    "Geomorphometric Analysis": "terrain_analysis",
    "Hydrological Analysis": "hydro_analysis",
    "Image Processing Tools": "image_analysis",
    "LiDAR Tools": "lidar_analysis",
    "Math and Stats Tools": "math_stat_analysis",
    "Stream Network Analysis": "stream_network_analysis"
}

book_cls = {
    "Data Tools": "data_tools",
    "GIS Analysis": "gis_analysis",
    "Geomorphometric Analysis": "geomorphometric_analysis",
    "Hydrological Analysis": "hydrological_analysis",
    "Image Processing Tools": "image_processing_tools",
    "LiDAR Tools": "lidar_tools",
    "Math and Stats Tools": "mathand_stats_tools",
    "Stream Network Analysis": "stream_network_analysis"
}

def get_github_url(tool_name, category):
    '''
    Generate source code link on Github 
    '''    
    url = wbt.view_code(tool_name).strip()
    return url


def get_book_url(tool_name, category):
    '''
    Get link to WhiteboxTools User Mannual 
    '''    
    prefix = "https://jblindsay.github.io/wbt_book/available_tools"
    url = "{}/{}.html#{}".format(prefix, category, tool_name)
    return url
```

**Comment by jblindsay** [comment]
I am sorry that this has caused problems for you maintainers of the front-ends. I probably should have put more thought into how I mapped the tools onto the User Manual. I have a (rather chaotic) script that automatically reads each of the Rust source files, parses the help documentation, and then writes the MarkDown version of the User Manual files. These files are then converted to the html site using Mdbook. The script looks something like this (parsed for brevity):

```python
toolboxes = wbt.toolbox('')
tb_set = set()
for tb in toolboxes.split('\n'):
    if tb.strip():
        tb_set.add(tb.strip().split(':')[1].strip())

tb_dict = {}
for tb in sorted(tb_set):
    tb_dict[tb] = []

out_dir = path.join(root_dir, "WhiteboxToolsUserManual/src/available_tools/")
for key, value in sorted(tb_dict.items()):
    nm = key.replace("/", "").replace(" ", "")
    nm = camel_to_snake(nm)
    if nm == "li_dar_tools":
        nm = "lidar_tools"
    out_file = os.path.join(out_dir, "{}.md".format(nm))
    print(out_file)
    f = open(out_file, 'w')
    f.write("# {}\n".format(key.replace("/", " &#8594; ")))

    # table of contents
    for v in sorted(value):
        f.write("- [{}](#{})\n".format(v[0], v[0]))
        description = tools[camel_to_snake(v[0])]
        toolEntryList.append(indexEntry.format(v[0], out_file.replace(
            out_dir, ""), v[0], description, key.replace("/", " &#8594; ")))

    f.write("")

    # contents
    for v in sorted(value):
        f.write("{}\n".format(v[1]))

    f.close()
```

Each of the tool docs are therefore written to each of the following files:

<img width="202" alt="screen shot 2019-02-26 at 12 03 08 pm" src="https://user-images.githubusercontent.com/8441542/53431537-bb45e400-39be-11e9-8cc8-7d2ea864a124.png">

I don't currently host the raw MarkDown files anywhere on my Github personal site, but you can take a look at the structure of the HTML version [here](https://github.com/jblindsay/jblindsay.github.io/tree/master/wbt_book). The tool specs are in the 'available_tools' folder.

**Comment by alexbruy** [comment]
That's fine. So I just need to create a small mapping between group names and documentation URL's. Seems ticket can be closed.

**Comment by jblindsay** [comment]
Wonderful, thanks for the update @alexbruy, I'll close now.
