### ISSUE TITLE
QGis MacOS WhiteBox plugin install failed

### ISSUE THREAD

**Issue by massbiodiversity** [jblindsay/whitebox-tools#250]
When I apply directory for Whitebox tools Options/Processing/Providers/ I get an error: Wrong value for parameter "OTB folder": Problem with OTB installation: " does not exist. How can I resolve this?

**Comment by jblindsay** [comment]
Can you include a screenshot of the error please?

**Comment by jblindsay** [comment]
There's no screenshot in your last comment.

**Comment by alexbruy** [comment]
This is not related to the WBT Provider plugin. The culprit is an OTB plugin and this should be reported to the OTB pluign developers.

**Comment by massbiodiversity** [comment]
Thank you

From the field,

Jim MacDougall
Topsfield, MA

On Jun 8, 2022, at 1:53 AM, Alexander Bruy ***@***.***> wrote:

﻿
This is not related to the WBT Provider plugin. The culprit is an OTB plugin and this should be reported to the OTB pluign developers.

**Comment by jblindsay** [comment]
Perfect, thank you Alex and thank you for taking the time for this. I hope that you are doing well.

I'm closing this issue now.
