### ISSUE TITLE
Trouble with lidar classification

### ISSUE THREAD

**Issue by mereiser** [jblindsay/whitebox-tools#276]
[I originally asked this in whiteboxR](https://github.com/giswqs/whiteboxR/discussions/87#discussion-4385869), but was told that it was a backend problem, so I'm asking again here.

I am trying to use the function wbt_lidar_clasify_subset() to classify the ground points in an unclassified point cloud using a .las file of just my classified ground points. However, regardless of how I assign my ground points I get the error:

```
Error running WhiteboxTools (LidarClassifySubset)
  whitebox.exe_path: "Path/4.2/whitebox/WBT/whitebox_tools.exe"; File exists? TRUE
  Arguments: --run=LidarClassifySubset  --base="/Path/all_points.las" --subset="/Path/las_gr.las" --output="/Path/output.las" --subset_class=2 -v

System command had status 101
**********************************
* Welcome to LidarClassifySubset *
* Powered by WhiteboxTools       *
* www.whiteboxgeo.com            *
**********************************
Reading input files...
Performing analysis...
Creating tree...
Performing analysis...
Progress: 0%
Progress: 1%
thread 'main' panicked at 'index out of bounds: the len is 1458 but the index is 1458', whitebox-lidar\src\las.rs:461:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lidar_classify_subset - Elapsed Time: NA [did not run]
Warning message:
In length(ret) > 0 && nchar(ret) > 0 :
  'length(x) = 13 > 1' in coercion to 'logical(1)'
```
What's going wrong here? I'm new to using whitebox, so I'm sorry if the solution is obvious!

**Comment by jblindsay** [comment]
Thanks for reporting. Are you able to provide me your base and subset LiDAR files so that I can test?

**Comment by mereiser** [comment]
Here's a plot and the ground points. The the ground points are classified as 0 not 2 because I was just checking if the different classification values between the two files was causing problems... but I get the same result if the ground points are classified as 0 or 2.
[sample_data.zip](https://github.com/jblindsay/whitebox-tools/files/9551866/sample_data.zip)

**Comment by jblindsay** [comment]
Are you quite certain that these are the files that caused the above error? These are LAZ files and in your error report above they are LAS files. I also get an error in running the tool with these files, but it is a different error than what you encountered.

**Comment by mereiser** [comment]
Ah, I think that's a result of how I zipped the folder... I'm not sure how to send them otherwise.

**Comment by mereiser** [comment]
Sorry about the weird format, but are these showing up as LAS files for you? 

[sample_data_2.zip](https://github.com/jblindsay/whitebox-tools/files/9552015/sample_data_2.zip)

**Comment by jblindsay** [comment]
No, it's not the result of the zipping. These are actually LAZ files and the error report (`--subset="/Path/las_gr.las" --output="/Path/output.las"`) references LAS files. They aren't the same.

**Comment by jblindsay** [comment]
Ah yes, I've got that now. Okay, let me see if I can figure out the issue now...

**Comment by jblindsay** [comment]
Don't worry, I've got them now and I'm on the case, hunting down the issue. I think the error is definitely on my end though. I can see a bug already. I'll update you in a while.

**Comment by jblindsay** [comment]
Okay, I just committed a fix for this issue now. It will be available in the next public release of WBT. If you cannot wait until then, you may build from source to have access to the fix.
