### ISSUE TITLE
LidarNearestNeighbourGridding produce bad result for rgb output

### ISSUE THREAD

**Issue by vprint** [jblindsay/whitebox-tools#278]
Hello,

LidarNearestNeighbourGridding doesn't save blue band 

Reproduction : 
1) select LidarNearestNeighbourGridding and select "rgb" in "interpolation parameters"
2) Open the output file : the blue band is empty

![bug_wbt](https://user-images.githubusercontent.com/42189444/189887170-d50bcaab-8691-4e67-b362-f114aa0a8622.gif)

**Comment by jblindsay** [comment]
Can you share your lidar data set with me to test please?

**Comment by vprint** [comment]
You can find data here : https://wxs.ign.fr/mct8y415ma63eudk50qaf2bi/telechargement/prepackage/JEU-TEST_LIDARHD_PACK_17-05-2022$LIDARHD_1-0_HYB_JEU-TEST-DALLE-0784_6392-2021/file/LIDARHD_1-0_HYB_JEU-TEST-DALLE-0784_6392-2021.7z

**Comment by jblindsay** [comment]
Okay, thank you very much for providing your sample file. I was able to use this to locate the source of the problem and have now fixed it and committed the updated code to the code base. It'll be publicly available with the next release of WhiteboxTools. If you can't wait until then, you may wish to build from source. Thank you for reporting the issue.

<img width="1175" alt="Screen Shot 2022-09-13 at 10 51 34 AM" src="https://user-images.githubusercontent.com/8441542/189934055-1d217ee0-3d6a-4abb-aa43-58aacf5f474d.png">

**Comment by vprint** [comment]
No problem at all, i can wait.

I will simply modify whitebox-tools-app/src/tools/lidar_analysis/lidar_idw_interpolation.rs and whitebox-tools-app/src/tools/lidar_analysis/lidar_nn_gridding.rs files on my PC and wait for the next release

**Comment by vprint** [comment]
Ok, i builded it from source and LidarNearestNeighbourGridding tools is now  working fine 💯 

However i also noticed invalid rgb output with the following tools : 


1) **LidarIdwInterpolation** (interpolation parameter = rgb, default settings for other parameters) :
<img width="527" alt="image" src="https://user-images.githubusercontent.com/42189444/190013684-a7a75bef-4428-414d-ab60-e46966fc8fab.png">_Transparency band set to none_

2) **LidarRbfInterpolation** (interpolation parameter = rgb, default settings for other parameters) :
<img width="524" alt="image" src="https://user-images.githubusercontent.com/42189444/190014596-80992c58-c2dd-4286-8569-0a658bdfcaee.png">_Transparency band set to none_

3) rgb not available for **LidarSibsonInterpolation**

4) **LidarTINGridding** (interpolation parameter = rgb, default settings for other parameters) :
<img width="527" alt="image" src="https://user-images.githubusercontent.com/42189444/190015215-b7216d8b-7a57-47af-b5f7-7f7531e91c2b.png">_Transparency band set to none_
