### ISSUE TITLE
[Errno 2] No such file or directory: './whitebox_tools'

### ISSUE THREAD

**Issue by mn5hk** [jblindsay/whitebox-tools#279]
I try to run the vector to raster conversion (on my jupyter notebook) as prescribed here: https://www.whiteboxgeo.com/manual/wbt_book/available_tools/data_tools.html?highlight=convert%20vector#vectorpolygonstoraster

'''
wbt.vector_polygons_to_raster(
    i, 
    output, 
    field="FID", 
    nodata=True, 
    cell_size=None, 
    base=nc.var_name.as_numpy(), 
    callback=default_callback
)
'''

Firstly, it shows default_callback is not there

I run the code without the line as:
'''
'''
wbt.vector_polygons_to_raster(
    i, 
    output, 
    field="FID", 
    nodata=True, 
    cell_size=None, 
    base=nc.var_name.as_numpy(), 
)
'''
and I get the following error:
[Errno 2] No such file or directory: './whitebox_tools'

What could the problem be?

**Comment by Afrancioni** [comment]
Hi @mn5hk 

It looks like the PATH to the WhiteboxTools binary is not properly set. Make sure to include the full PATH including the .exe extension when setting the location of WBT.
