### ISSUE TITLE
Remove broken links to Whitebox GAT

### ISSUE THREAD

**Issue by caesar** [jblindsay/whitebox-tools#281]
The readme has several broken links to Whitebox GAT, including in the opening paragraph. I believe (based on #162) that Whitebox GAT doesn't exist anymore, which makes these references rather confusing to a newcomer.
It would be good to remove these references, and perhaps also to add a note somewhere further down the page to the effect that Whitebox GAT has been discontinued.

**Comment by jblindsay** [comment]
Thank you for reporting this issue. The GitHub README was sorely out of date with respect to the project documentation. User are far better off referring to the User Manual, which I now direct them to.
