### ISSUE TITLE
Noisy geomorphons

### ISSUE THREAD

**Issue by rengifoo** [jblindsay/whitebox-tools#283]
Hei guys
first of all thanks for implementing geomorphon in WTB Core. I wonder just one thing, why is so that geomorphon  output produced with WTB is slightly more noise, than the one produced in GRASS GIS/QGIS?

**Comment by terencebarrett** [comment]
I am also wondering about what may be a related issue. I am currently comparing the Geomorphon implementations in Whitebox v2.1.0 and GRASS v7.8. I find that the WB "skip" parameter, which seems to be the equivalent of the GRASS "skip" parameter, and which the GRASS docs say "eliminates forms of very small extend, smaller than skip parameter" (which could be seen as noise), does nothing, no matter the value I use with it.

**Comment by jfbourdon** [comment]
I'm also interested as I'm about to use Geomorphon for a project. I don't have time right now to look into it but here are some references (mainly for myself later):
- [WhiteboxTools implementation](https://github.com/jblindsay/whitebox-tools/blob/739c6854d5617e34fe5f696b14e862566e1249f5/whitebox-tools-app/src/tools/terrain_analysis/geomorphons.rs) and [documentation](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/geomorphometric_analysis.html#Geomorphons)
- [GRASS implementation](https://github.com/OSGeo/grass/tree/40b598233c196df1c08a6222da24f2307841d1c5/raster/r.geomorphon) and [documentation](https://grass.osgeo.org/grass80/manuals/r.geomorphon.html)

**Comment by jblindsay** [comment]
Dan Newman, the author of this Whitebox tool has issued an update. It will be available in v2.2 which will be released, not next week, but the week after. The fix is in the code base now.

**Comment by terencebarrett** [comment]
Such prompt attention, much appreciated. I'll test when the new version is released - thanks!

**Comment by terencebarrett** [comment]
Tested the Geomorphons tool in OpenCore v2.2 - the "skip" parameter is now working, thanks! 
Edge effects are larger, but otherwise the output appears equivalent to Grass' output, at least for my single test case.
