### ISSUE TITLE
ClipLidarToPolygon Failed to Fill Whole Buffer

### ISSUE THREAD

**Issue by geethaganji** [jblindsay/whitebox-tools#291]
Environment: python 3.9

Method:
wbt.clip_lidar_to_polygon(
    input_las file, 
    .shp file, 
    .las file)

Error:
thread 'main' panicked at 'failed to fill whole buffer', whitebox-tools-app/src/main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Process:
Input file is from 3DEP LIDAR data which goes through below methods and the output of Lidartingridding (method 6 from the list below) is input to ClipLidarToPolygon

1. ClassifyOverlapPoints (input is the 3DEP LIDAR .las file)
2. FilterLidarClasses ( input is the output of ClassifyOverlapPoints)
3. Lidartophattransform (input is the output of FilterLidarClasses )
4. Lidartingridding (input is the output of Lidartophattransform )
5. Lidarelevationslice (input is the output of Lidartingridding )
6. Lidartingridding (input is the output of Lidarelevationslice)

Any help would be appreciated.

**Comment by jblindsay** [comment]
Can you post your actual script and also the compete tool output?

**Comment by geethaganji** [comment]
[Test_data.zip](https://github.com/jblindsay/whitebox-tools/files/9913136/Test_data.zip)

Attached file contains the python script, data file and also the test script to execute the file.

**Comment by jblindsay** [comment]
I'm not sure what to make of that script or the data. It does not appear to even use the clip_lidar_to_polygon tool. It doesn't use typically whitebox_tools scripting conventions either.

**Comment by jblindsay** [comment]
It looks like you are running Whitebox using process calls. Why aren't you using the conventional Python API (whitebox_tools.py) contained within the WBT folder?

**Comment by jblindsay** [comment]
I don't think this is an error with the tool. Instead I think it is an error with how you are calling the tool, or the data that you are feeding to it. However, in truth, your script is so convoluted to read that I can't make heads or tails of it. I'd suggest using the Python API instead of direct process calls. Or better yet, use [Whitebox Workflows for Python](https://www.whiteboxgeo.com/whitebox-workflows-for-python/), which will **significantly** improve your code simplicity.

**Comment by geethaganji** [comment]
![cliplidartopolygon](https://user-images.githubusercontent.com/33674532/199326877-ec0a683d-1fb4-4f88-b243-b1834cf1913b.JPG)

I tried the way you suggested. Attached is the image with code and error.

**Comment by jblindsay** [comment]
I can't help you without looking at the actual data. I'd need to see your input las file and shapefile.
