### ISSUE TITLE
geomorphon fails in ArcGIS Pro 

### ISSUE THREAD

**Issue by geoendemics** [jblindsay/whitebox-tools#292]
Hi guys !
congratulations for this great release. Below the error I get when trying to run  geomorphons in ArcGIS pro

Traceback (most recent call last):
  File "<string>", line 13623, in execute
TypeError: geomorphons() got an unexpected keyword argument 'tdist'

Failed to execute (Geomorphons).

Best 
regards
Rengifo Ortega

**Comment by jblindsay** [comment]
I think that this is an issue for the ArcGIS front-end and not the WhiteboxTools back-end. I'm closing it therefore, but if it turns out to be a back-end issue, please re-open.
