### ISSUE TITLE
How to calculate D8 flow accumulation memory usage

### ISSUE THREAD

**Issue by InsolublePancake** [jblindsay/whitebox-tools#295]
Hello,
I wonder if you can explain how I can calculate the memory requirements for running the d8_flow_accumulation tool. My process runs a number of tools with the goal of extracting streams and watersheds from a tiled DEM. I have been calculating memory requirements for the d8_pointer tool in the way that you have advised me before, which is 16 bytes per pixel of input raster (that is 8 bytes for the input raster and 8 for the output). However, I run out of memory when running the same output through the d8_flow_accumlation tool with the same memory available, so I'm assuming that it has greater requirements.

Thanks

**Comment by jblindsay** [comment]
Hello,
I'm sorry, but this is not an issue, but rather just a question. Questions should be posted either to the Google Groups list serv or directly to support@whiteboxgeo.com. I'm closing this now, but I'll be happy to answer your question should you post it as above. Thanks for your understanding.

**Comment by InsolublePancake** [comment]
Ok, sorry about that. I've emailed the above address.
