### ISSUE TITLE
LidarColourize - thread 'main' panicked at 'Unrecognized raster type'

### ISSUE THREAD

**Issue by ejnaren** [jblindsay/whitebox-tools#296]
Hi. These tools seem very promising, but I get an eroor trying to use the LidarColourize module in Qgis 3.28.
I have attached the rasterimage in question. Anby ideas how I can fix this?

![Satmap Clean](https://user-images.githubusercontent.com/737773/201465522-ef91d260-c78c-421c-afea-c2d62ab08600.jpg)

The error message is:
QGIS-versjon: 3.28.0-Firenze
QGIS-kodeversjon: ed3ad0430f3
Qt-versjon: 5.15.3
Python-versjon: 3.9.5
GDAL-versjon: 3.5.2
GEOS-versjon: 3.10.3-CAPI-1.16.1
PROJ-versjon: Rel. 9.1.0, September 1st, 2022
PDAL-versjon: 2.4.3 (git-version: 434757)
Algoritme startet: 2022-11-12T09:17:10
Algoritmen «LidarColourize» starter …
Inndataparametre:
{ 'in_image' : 'C:/Users/ejnar/Documents/Midlertidige prosjektmappe/Idrettsakse/Satmap Clean.jpg', 'in_lidar' : 'C:\\Users\\ejnar\\Documents\\Midlertidige prosjektmappe\\Idrettsakse\\32-1-474-170-03 - Cloud.las', 'output' : 'TEMPORARY_OUTPUT' }

WhiteboxTools command:
"C:/mywhiteboxfolder/WBT/whitebox_tools.exe" -v --run=LidarColourize --in_lidar="C:\Users\ejnar\Documents\Midlertidige prosjektmappe\Idrettsakse\32-1-474-170-03 - Cloud.las" --in_image="C:\Users\ejnar\Documents\Midlertidige prosjektmappe\Idrettsakse\Satmap Clean.jpg" --output="C:\Users\ejnar\AppData\Local\Temp\processing_UMYCUA\649891cdf8704c1bad8aeb5948593a1e\output.las"
WhiteboxTools output:
*****************************
* Welcome to LidarColourize *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com *
*****************************
Reading input files...
thread 'main' panicked at 'Unrecognized raster type', whitebox-tools-app\src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process returned error code 101
Execution completed in 1.70 sekunder
Resultat:
{'output': 'TEMPORARY_OUTPUT'}

Last resultatlag
Algoritmen «LidarColourize» er utført

**Comment by Afrancioni** [comment]
Hello @ejnaren ,

WhiteboxTools does not support the .jpg file format. That error is not an error with the tool but rather a non-feature of the platform currently. I would suggest converting these files to something WhiteboxTools supports. Please see the list of supported formats in the User Manual https://www.whiteboxgeo.com/manual/wbt_book/supported_formats.html

If you would like to open a feature request support the jpeg format you can do so.
