### ISSUE TITLE
Clump: typo in nodata value

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#306]
I assume [this ](https://github.com/jblindsay/whitebox-tools/blob/5a54e687e71abcae4460020c2bd41ee63728411d/whitebox-tools-app/src/tools/gis_analysis/clump.rs#L228 )is supposed to be -9999 not -999

**Comment by jblindsay** [comment]
No, -999 works fine for this nodata value in this case as far as I can see.
