### ISSUE TITLE
Problem writing denoised tif

### ISSUE THREAD

**Issue by borlafgis** [jblindsay/whitebox-tools#31]
Hello

I tried to denoise a DEM using the following command

`C:/WhiteboxTools/whitebox_tools.exe -r=FeaturePreservingDenoise -v --dem="/path/dem.tif" -o=demf.tif --filter=15 --norm_diff=20.0 --num_iter=4`

the product is a DEM with a similar weight as the original one, however, I have been unable to read it with GDAL. Running gdalinfo on the output produces the following:

```
gdalinfo demf.tif
ERROR 1: demf.tif:Not a TIFF file, bad version number 10752 (0x2a00)
gdalinfo failed - unable to open 'demf.tif'.
```

The output of gdalinfo for the original file is the following

```
gdalinfo "/path/dem.tif"
Driver: GTiff/GeoTIFF
Files: /path/dem.tif
Size is 9001, 9001
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (21.999944444444445,45.000055555555555)
Pixel Size = (0.000111111111111,-0.000111111111111)
Metadata:
  AREA_OR_POINT=Point
  TIFFTAG_DATETIME=2015:05:26 21:46:30
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=[sensitive]
  TIFFTAG_XRESOLUTION=50
  TIFFTAG_YRESOLUTION=50
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  21.9999444,  45.0000556)
Lower Left  (  21.9999444,  43.9999444)
Upper Right (  23.0000556,  45.0000556)
Lower Right (  23.0000556,  43.9999444)
Center      (  22.5000000,  44.5000000)
Band 1 Block=9001x1 Type=Float32, ColorInterp=Gray

```

I hope this info is helpful, I tried to report this problem as instructed in the documentation

Kind regards,
Ignacio

**Comment by jblindsay** [comment]
@borlafgis Thank you for reporting this issue. Issues with GeoTIFF support are a constant struggle for me because the GeoTIFF format is so incredibly flexible. Would it be possible for you to share your file **dem.tif** with me? I will see if I can find the problem as soon as I have available time. However, at the moment work is really getting quite busy. As such, your best bet in the meantime is to save your output as a **.flt** (or one of the other supported file formats). GeoTIFF is a *very problematic* file format to add native support for and it's somewhat unfortunate that it has become the standard for raster data. I would prefer to add support for GDAL into WhiteboxTools but for certain design objective reasons that is not possible.

**Comment by borlafgis** [comment]
@jblindsay Thanks a lot for your quick answer! I am sorry, but it is not possible for me to share this specific DEM, because it is protected under a confidentiality clausule (it is a tile of the tandem-x dem at 12 m resolution). I wish I could, but I would be sanctioned. A possible alternative is to try with a tile of from the TDX90m, which is readily available. I can check if it does share the same labels as the max resolution one.

Also, thanks a lot for your solution, as you say, trying with a less problematic format does solve the problem. I tried with a RST, and I was able to open the result with no problem

**Comment by jblindsay** [comment]
@borlafgis It would be great if you wouldn't mind testing to see if you encounter the same issue with the TDX90m product and if so, if you could forward me your test file, I can try to solve the issue. I'm glad to hear that saving the output as an IDRISI file worked for you.

**Comment by borlafgis** [comment]
@jblindsay The problem also appears for the 90m DEM. The error given by gdalinfo is:

```
gdalinfo tdx90.tif
ERROR 1: tdx90.tif:Not a TIFF file, bad version number 10752 (0x2a00)
gdalinfo failed - unable to open 'tdx90.tif'.
```
The output of gdalinfo for the original file is the following:

```
$ gdalinfo TDM1_DEM__30_N43E023_DEM.tif
Driver: GTiff/GeoTIFF
Files: TDM1_DEM__30_N43E023_DEM.tif
Size is 1201, 1201
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (22.999583333333334,44.000416666666666)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  AREA_OR_POINT=Point
  TIFFTAG_DATETIME=2015:05:26 21:06:29
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=W42/DLR
  TIFFTAG_XRESOLUTION=50
  TIFFTAG_YRESOLUTION=50
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  22.9995833,  44.0004167)
Lower Left  (  22.9995833,  42.9995833)
Upper Right (  24.0004167,  44.0004167)
Lower Right (  24.0004167,  42.9995833)
Center      (  23.5000000,  43.5000000)
Band 1 Block=1201x2 Type=Float32, ColorInterp=Gray
```

You can find the file following the following URL (the registration is free)
[](https://download.geoservice.dlr.de/TDM90/files/N43/E020/TDM1_DEM__30_N43E023.zip)

**Comment by jblindsay** [comment]
@borlafgis I've been able to track down the issue somewhat. It would seem that the TanDEMX data are in a Big Endian GeoTIFF format, which WhiteboxTools reads fine but seems to have issue with writing. The endianness of the output file is taken from the input file. Admittedly, I don't see Big Endian GeoTIFF files that often and had assumed that I was writing these files okay. I've temporarily fixed this by always outputting to Little Endian formats (which are written fine) and will investigate to see if I can fine the error with the Big Endian GeoTIFF writer. Honestly though, I'm not sure why a little-endian-always solution wouldn't work. I can't imagine a situation where a Big Endian format would be absolutely necessary.

**Comment by jblindsay** [comment]
@borlafgis I've just committed a fix. I believe that I was just not correctly writing the 'MM' file header for a Big Endian GeoTIFF.
