### ISSUE TITLE
ElevationAboveStream only computing part of the domain

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#319]
HAND values are not computed for the full domain. I expect values to be calculated all the way up the slope. Instead there's a strange 'block' effect at the edges. 

DEM: 
![image](https://user-images.githubusercontent.com/47092034/214259968-4023e91d-6d41-415a-b1a3-4cf083ee92c9.png)

Streams:
![image](https://user-images.githubusercontent.com/47092034/214260154-40fbde4b-f2fe-47e2-b740-332201004aab.png)

Result:
![image](https://user-images.githubusercontent.com/47092034/214260264-0705a3d0-d031-4a9a-afe1-7c5df4ad6838.png)
![image](https://user-images.githubusercontent.com/47092034/214260300-d3d7b077-4af2-4631-bc84-645c0b45de38.png)

The streams are derived from a simple contour/threshold of the DEM, so I don't suspect this is an issue. Command is below.

Any advice you can give on this is highly appreciated,

WhiteboxTools command:
"L:/06_SOFT/whitebox/v2.2.0/whitebox_tools.exe" --run=ElevationAboveStream --dem="L:\02_WORK\NRCan\2207_RICorDE\04_CALC\ftMac\dem\AEP\AEP_DEM_r01_aoi01_filld_trim_0124b_small.tif" --streams="C:\Users\cefect\AppData\Local\Temp\processing_wpEbyN\988543ca63c24b0796080f5d6306573d\OUTPUT.tif" --output="C:\Users\cefect\AppData\Local\Temp\processing_wpEbyN\a2af827604414b9480891af67e720ecf\output.tif" -v
WhiteboxTools command output:
***********************************

* Welcome to ElevationAboveStream *

* Powered by WhiteboxTools *

* www.whiteboxgeo.com *

***********************************

Reading DEM data...

Reading streams data...

Saving data...

Output file written

Elapsed Time (excluding I/O): 0.25s

**********************************************************************************

WARNING: Interior pit cells were found within the input DEM. It is likely that the 

DEM needs to be processed to remove topographic depressions and flats prior to

running this tool.

**********************************************************************************

Execution completed in 0.16 seconds

NOTE: I ran the DEM through all the hydro-conditioning tools... but kept getting the 'Interior pit cells' warning. 
NOTE: I also tried with v2.1.0 and v2.0.0 and got the same.

**Comment by Atreyagaurav** [comment]
I've found this problem before, but there is no reply from anyone. 

Here is the issue. I looked at the code and saw that this tool uses the `no_data` value from the streams to mask the output DEM instead of using the no_data from the input DEM to mask them. I've included the fix there I used to prepare my map, so if you have rust you can patch it and test it out.

https://github.com/jblindsay/whitebox-tools/issues/245

**Comment by cefect** [comment]
I don't suspect it is a nodata problem as there are NO nodata cells in any of my inputs. I suspect the problem is DEM regions without flow path connectivity to the stream cell inputs.
