### ISSUE TITLE
Cost distance produces integer data type

### ISSUE THREAD

**Issue by lahm3d** [jblindsay/whitebox-tools#32]
Encountered a strange problem while trying to run Cost Distance tool. The output is consistently an integer data type instead of a float point. Currently working on  `v0.15.0` and here are the [source and cost surfaces](https://drive.google.com/drive/folders/1kPvlBQhJiU5FQFlbOWookVxcBafajDnt?usp=sharing). I can't seem to find any issue with the raw data. Any ideas?

**Comment by jblindsay** [comment]
This tool created output rasters that take their DataType format from the input cost surface file. So if the input cost raster is of integer type, the output would be as well. I've just submitted a change to the source code that will override this default behaviour, forcing the output raster to be of 32-bit floating-point output. See [here](https://github.com/jblindsay/whitebox-tools/blob/3b5f8d92a686d3c6b1f50382721389ccf122a5d3/src/tools/gis_analysis/cost_distance.rs#L261) for details.

**Comment by lahm3d** [comment]
Cheers. Thanks for the update!
