### ISSUE TITLE
Contributing to the user manual

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#320]
I'm wondering if there is a readme or some guidelines with info on how I might contribute to the [user manual](https://www.whiteboxgeo.com/manual/wbt_book/intro.html) source (e.g., fixing typos)?

Thanks for the awesome project.

**Comment by jblindsay** [comment]
No, I'm sorry but there are no such guidelines. You can just email your suggested changes to support@whiteboxgeo.com. Thanks.

**Comment by jblindsay** [comment]
Actually, the part of the user manual related to the documentation of the tools is auto-generated from the docs of the corresponding tools in the source code. And so, if you see typos or suggestions for clarification in the tool docs, just issue a pull request with your changes there.
