### ISSUE TITLE
Exec format error: './whitebox_tools'

### ISSUE THREAD

**Issue by saalimzafar** [jblindsay/whitebox-tools#324]
I'm following the introductory tutorial but getting the error for input
i="StElisAk.laz" | i="StElisAk.las", 
+ is this a typo .laz or .las as downloaded file has .laz extension.

**Comment by jblindsay** [comment]
You're right that it should be StElisAk.laz rather than StElisAk.las. I've updated the user manual now. Thanks for spotting this.
