### ISSUE TITLE
win10 error: Reading data... 'gbk' codec can't decode byte 0x82 in position 59: illegal multibyte sequence 1

### ISSUE THREAD

**Issue by fenglinhuoshan123** [jblindsay/whitebox-tools#33]

**Comment by jblindsay** [comment]
I'm going to need a lot more details than this to fix this bug. For example, what tool were you running when you received this error? What type of input data were you using? What were the parameters? What version of WhiteboxTools?

**Comment by jblindsay** [comment]
I am closing this because there is not enough information to determine the issue. Feel free to add more details and re-open.
