### ISSUE TITLE
[feature request]  Adding option to VectorPointsToRaster module

### ISSUE THREAD

**Issue by skampus** [jblindsay/whitebox-tools#330]
dear sirs, first of all let me thank you for your wonderful software.
I would ask if you think it is possible to add the "mean" option to 'VectorPointsToRaster".
Currently the available options are "max", "min", "first", "last", "sum" and "number", but sometimes it is necessary instead to calculate, in a group of overlapping points, the average; for example in a trajectory numerical modeling result with trajectories passing over the same point/cell.

Thank you in advance

stefano

**Comment by jblindsay** [comment]
I've just implemented this feature request. It'll be available in the next public release, scheduled for sometime around the end of the month. If you can't wait until then, you may build from source to take advantage of the feature.

**Comment by skampus** [comment]
thank you very much, I'll wait

stefano
