### ISSUE TITLE
Time in daylight - panick

### ISSUE THREAD

**Issue by CarlosGrohmann** [jblindsay/whitebox-tools#336]
Hi John,

Tried the TimeInDaylight tool, but got these errors:

```
Calculating the local almanac...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ComponentRange { name: "ordinal", minimum: 1, maximum: 365, value: 366, conditional_range: true }', whitebox-tools-app\src\tools\terrain_analysis\time_in_daylight.rs:935:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running it on Windows10, latest WB release.

**Comment by jblindsay** [comment]
Yes, it is now resolved on the main branch and will be in the next public release of WbTools. If you need it now, you can either compile from source or use Whitebox Workflows for Python, which also has the fix and is available now.

**Comment by wiesehahn** [comment]
is there an approximate time scale when the next public release will be?

**Comment by tobias-brunner** [comment]
The possibility to download older builds would be great, too. The official Whitebox-page only hosts the newest build.

**Comment by tobias-brunner** [comment]
So I just compiled it from source following the manual on this github page. I had to do it on my personal computer though. And switch off the antivirus.

**Comment by darzmolar** [comment]
Hello! Is this bugfix released in the newest version of the package?
Thank you.
