### ISSUE TITLE
Problems reading LAS files when using lidar_join

### ISSUE THREAD

**Issue by 03bennet** [jblindsay/whitebox-tools#343]
I'm trying to use lidar_join. However when I run the following code...

```
wbt = WhiteboxTools()
wbt.set_verbose_mode(True)
wbt.set_compress_rasters(True) 

wbt.lidar_join(
inputs = "/home/tom/DeduplicateMerge/LAS",
output = os.path.join(output_dir, "test.las")
)
```

I get this error:

**thread 'main' panicked at 'No such file or directory (/home/tom/DeduplicateMerge/LAZ)', whitebox-tools-app/src/main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

It does, bizarrely, seem to run when I change the input to a specific file like below. 

`inputs = "/home/tom/DeduplicateMerge/LAZ/test.las"`

Not sure why it would run on a single LAS file and not on multiple tiles

**Comment by jfbourdon** [comment]
This tool won't lookup for all LAS files within a directory. You need to specify the path for each file or only the name of each file if you specified the working directory like in:

```python
wd = "/home/tom/DeduplicateMerge/LAZ"

wbt = WhiteboxTools()
wbt.set_verbose_mode(True)
wbt.set_compress_rasters(True) 
wbt.set_working_directory(wd)

files = ",".join([file for file in os.listdir(wd) if file.endswith(".las")])
wbt.lidar_join(
    inputs = files,
    output = os.path.join(output_dir, "test.las")
    )
```

If you have other usage question, you can ask on [WhiteboxTools' Google Group](https://groups.google.com/g/whiteboxtools).
