### ISSUE TITLE
Whitebox Runner Crashing

### ISSUE THREAD

**Issue by whitson-buck** [jblindsay/whitebox-tools#346]
I am currently trying to perform an elongation ratio analysis on a polygon shapefile I have stored. The file displays in the file selector tool:

![image](https://user-images.githubusercontent.com/67715134/234347286-fd10e97c-2e1e-4771-9e24-ae905642eea6.png)

But when I select the file, the runner crashes immediately.

**Comment by jblindsay** [comment]
I cannot replicate the error. Can you send me your file please? Also, is it a polygon file? If it is not, then an error should pop up, but it shouldn't crash the WbRunner.

**Comment by whitson-buck** [comment]
Here is a link to the file: https://drive.google.com/file/d/1UuPoQ0x4obdTa5GkFN8_mR_n4FLYq3x7/view?usp=sharing

**Comment by jblindsay** [comment]
Perfect, thank you for providing the file. I can confirm that loading that file seems to crash WbRunner. I'll look into the cause and a fix as soon as I get an opportunity. Thanks for reporting the issue.

**Comment by giswqs** [comment]
Is it because the shapefile is incomplete? A shapefile should have .shp, .shx, and .dbf. But you only provide the .shp.

**Comment by jblindsay** [comment]
Yes, you need more than just the shapefile. You also need, at a minimum, the associated .dbf file. Remember, shapefiles are more than .shp! The classic GIS problem.

**Comment by jblindsay** [comment]
Nonetheless, this should cause a warning error and not a program crash.

**Comment by giswqs** [comment]
Yeah, a classic GIS problem. It would be helpful to give a warning rather than a program crash when the shapefile is incomplete.
https://www.reddit.com/r/gis/comments/sbp8r9/please_find_the_shapefile_attached/
![image](https://user-images.githubusercontent.com/5016453/234363882-e0ee60d6-7292-4f12-81fb-d164255f7972.png)

**Comment by whitson-buck** [comment]
Hi,

The runner does not crash, but now I do not see where the output is. Here is a link to all files if you would like to try for yourself:

https://drive.google.com/drive/folders/1sT2T9Y7kS74MIy-dMEeC5rGGV__HGTRi?usp=sharing

Thanks!

**Comment by jblindsay** [comment]
The output of this tool is written to the file's attribute table (*.dbf). For details, please take a look at the tool description in the [user manual](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/gis_analysis_patch_shape_tools.html#ElongationRatio).
