### ISSUE TITLE
Memory allocation issues with fill_burn

### ISSUE THREAD

**Issue by InsolublePancake** [jblindsay/whitebox-tools#356]
Hello,

I'm using the latest whitebox tools via the free Python API and running on linux.

I have a workflow that processes a DEM to get a d8 pointer, and one of the steps is fill_burn. It fails with the message "memory allocation of 44108107200 bytes failed" yet immediately prior to this I've checked memory availability and it has been 67294883840. No one else is currently using the machine and there are no major system processes going on in the background.

The DEM dimensions are (45128, 40725) and the shapefile is 75mb.

I use breach_depressions_least_cost, followed by fill_depressions_planchon_and_darboux, before I run fill_burn and both run without error. I am guessing that the quoted 44108107200 is not actually what the tool requires, but I'm not able to determine how much is genuinely needed. 

You've told me previously that breach_depressions_least_cost requires 16 bytes per pixel. When I calculate the size of DEM I can run with a given amount of RAM, I use 18 bytes per pixel and assume that only 75% of the memory will be consistently available, but that still doesn't seem to be enough.

Is fill_burn particularly memory intensive? Can you tell me how I can calculate its memory requirements. I assume that the shapefile needs to be factored in, but I'm guessing there is more to it than that because my margin should have been sufficient to handle and extra 75mb.

I also use the following tools. Are any likely to be more memory hungry than the tools I've already mentioned? I really just want to find the peak memory usage of the entire suite of tools so that I can calculate tile size at the start.

- d8_flow_accumulation
- extract_streams
- remove_short_streams
- raster_streams_to_vector
- flatten_lakes
- watershed

Apologies for all the questions.
Many thanks,
Rick

**Comment by jblindsay** [comment]
I've pushed a change to early-release some of the data structures used by this tool, however, even still there is a need for significant overlap. While the memory footprint will be somewhat reduced, I think this tool will always be somewhat memory intensive. I will point out that the Whitebox Workflows for Python version of this tool will require slightly less memory because of the different way that it represents raster data in memory.

**Comment by InsolublePancake** [comment]
Thanks for getting back to me. 58 bytes is way more than I expected! That's going to have a serious impact on tile sizes I can use. I guess I will have to tile the DEM twice in order that I have the maximum tile size for creating drainage lines and watersheds.
Thanks for your help.

**Comment by InsolublePancake** [comment]
Does it matter which order I run breach_depressions_least_cost and fill_burn?

**Comment by jblindsay** [comment]
I'd probably run fill_burn before breaching. I would assume that the stream burning operation would solve many of the depressions that would otherwise need to be breached.

**Comment by InsolublePancake** [comment]
Ok great, thanks
