### ISSUE TITLE
Trace Downslope Flowpaths fails to index 

### ISSUE THREAD

**Issue by tnair-c2s** [jblindsay/whitebox-tools#368]
I'm trying to run TraceDownslopeFlowpaths through the qgis plugin but it's failing with the following trace in [trace_downslope_flowpaths.rs](https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-tools-app/src/tools/hydro_analysis/trace_downslope_flowpaths.rs#L382):

```python
**************************************
* Welcome to TraceDownslopeFlowpaths *
* Powered by WhiteboxTools           *
* www.whiteboxgeo.com                *
**************************************
Reading flow direction data...
Locating seed points: 0%
Locating seed points: 100%
thread 'main' panicked at 'index out of bounds: the len is 129 but the index is 248', whitebox-tools-app/src/tools/hydro_analysis/trace_downslope_flowpaths.rs:382:33
stack backtrace:
   0:     0x55ab3e673b0a - <unknown>
   1:     0x55ab3e69af1e - <unknown>
   2:     0x55ab3e6709a5 - <unknown>
   3:     0x55ab3e6738d5 - <unknown>
   4:     0x55ab3e6750bf - <unknown>
   5:     0x55ab3e674dfb - <unknown>
   6:     0x55ab3e6757c9 - <unknown>
   7:     0x55ab3e675569 - <unknown>
   8:     0x55ab3e673fbc - <unknown>
   9:     0x55ab3e675272 - <unknown>
  10:     0x55ab3d685493 - <unknown>
  11:     0x55ab3d685602 - <unknown>
  12:     0x55ab3d9f4c9a - <unknown>
  13:     0x55ab3db505d8 - <unknown>
  14:     0x55ab3dc8b618 - <unknown>
  15:     0x55ab3dc8862a - <unknown>
  16:     0x55ab3e161e63 - <unknown>
  17:     0x55ab3dbc6849 - <unknown>
  18:     0x55ab3e66b7cc - <unknown>
  19:     0x55ab3dc8c855 - <unknown>
  20:     0x7f92e5836d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7f92e5836e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  22:     0x55ab3d685b25 - <unknown>
  23:                0x0 - <unknown>

```

Process to generate:
1. Create d8 pointer with FD8Pointer from a clipped NED DEM file,  which creates the following raster
![image](https://github.com/jblindsay/whitebox-tools/assets/88670474/c0c5a4a2-26f4-4406-9694-c067876ff4f9)
2. Create a single seed point and write to shapefile.

Environment: latest version of whitebox on Ubuntu 22.04 

I've tried adding a "z" coordinate to my point based on the DEM value, but the error remains the same. Is there a specific way we are supposed to be creating the seed point?

**Comment by jfbourdon** [comment]
The [documentation of TraceDownslopeFlowpaths](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#TraceDownslopeFlowpaths) states that a D8 flow pointer is needed (as produced by D8Pointer or Rho8Pointer) as it only expects pointer values of `0, 1, 2, 4, 8, 16, 32, 64, 128`. However, a pointer raster produced with [FD8Pointer](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/hydrological_analysis.html#Fd8Pointer) can produce values of `11, 40, 193` or any other summation of the base-2 D8 pointer values which will cause a crash like you experienced.
