### ISSUE TITLE
local_quadratic_regression fails

### ISSUE THREAD

**Issue by CarlosGrohmann** [jblindsay/whitebox-tools#371]
Hi,

As I was preparing a notebook using WBT and the "whitebox" python package (not whitebox-workflows), I got this error while running local_quadratic_regression:

```
./whitebox_tools --run="LocalQuadraticRegression" --wd="/mnt/d/Dropbox/USP/extensao/videos_whitebox" --dem='CopDEM_clip_petar.tif' --output='CopDEM_clip_petar_wood_w9' --filter=9 -v --compress_rasters=True

***************************************
* Welcome to LocalQuadraticRegression *
* Powered by WhiteboxTools            *
* [www.whiteboxgeo.com](https://www.whiteboxgeo.com/)                 *
***************************************
Reading data...
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', whitebox-plugins/src/local_quadratic_regression/main.rs:218:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failure to run plugin subprocess.

0
```

The python package was installed today with pip and then I downloaded WBT binaries with:
`whitebox.download_wbt(linux_musl=True, reset=True)`

**Comment by CarlosGrohmann** [comment]
Just to complement. I tested today with a Windows version (with WhiteboxRunner), and it ran fine. So it is likely related to the MUSL version

**Comment by jblindsay** [comment]
Hi Carlos, as you know, I didn't write this tool, but rather Dan Newman did. So I'm not as familiar with this tool as I am many of the others. However, I am confused as to why it would work on Windows and not on Linux for you. The code is exactly the same regardless. Do you have a copy of `CopDEM_clip_petar.tif` that you can share with me for testing?

**Comment by CarlosGrohmann** [comment]
Sure, here it is: https://www.dropbox.com/scl/fi/ixyh60i4qemm28k3x6vpm/CopDEM_clip_petar.tif?rlkey=oaxjkq8lzjl3gg84f9fmdch1t&dl=0

Just to provide a bit more info: the linux system is running on WSL2. I created a python virtual environment, installed whitebox with pip, and when I called `import whitebox` for the first time, it downloaded WBT but it didn't worked (GLIBC error), so I went with `whitebox.download_wbt(linux_musl=True, reset=True)` and then it worked. Well, except for local_quadratic_regression.

**Comment by jfbourdon** [comment]
Looking at the line that crashed and the command used, I'm pretty sure the issue is simply that the file extension of the output raster wasn't provided but is required, so `--output='CopDEM_clip_petar_wood_w9.tif'` instead of `--output='CopDEM_clip_petar_wood_w9'`.

**Comment by CarlosGrohmann** [comment]
WHAAAT? That simple?
And it works! 

But let's point out that this tool is not behaving like the others. For every other tool I used, I was just creating the name without the extension, like 
```
az = 315
alt = 35
zf = 1

wbt.hillshade(
dem = cop_tif,
output = f'{cop}_shade_{az}_{alt}_z{zf}',
azimuth=az,
altitude=alt,
zfactor=zf)
```

**Comment by jblindsay** [comment]
Hi Carlos,

For all the tools that I've written, I have a bit of code in there that adds a 'tif' extension if the user hasn't provided it. I think perhaps Dan just left this out for this tool. I'll add it in myself when I get a chance.

**Comment by CarlosGrohmann** [comment]
Yes, likely just a simple check that is missing. The good thing is that it works! Closing the issue.
