### ISSUE TITLE
Incorporating user define streamlines into the watershed?

### ISSUE THREAD

**Issue by WindingWinter** [jblindsay/whitebox-tools#375]
For watershed delineation, is it possible to incorporate user defined streamlines?

Basically my site is a fully develop urban site, with road, residential areas ( which are flat or contain little curvature), and of course, drain. I'm thinking to apply the watershed algorithm like D8 on such a site, and I will make the drain a bit deeper to simulate the user defined streamlines. Or the whitebox tool actually allows us to specify the user defined streamlines and internally it recognizes them as such? That would be good for us.

Does such approach even work? Or do we have a more robust approach?

**Comment by jblindsay** [comment]
I believe you're describing the process of stream burning, a common DEM pre-processing method. In WhiteboxTools, you have access to several such burning methods, including TopologicalBreachBurn (in the extension), FillBurn, and BurnStreamsAtRoads.

**Comment by WindingWinter** [comment]
Thank you for your swift reply! For the kind of urban sites, are there any tools to further "correct" the DEM, so that the watershed analysis result is more correct? It might be necessary as[ flow in urban areas is largely determined by sub-surface built infrastructure, which is not apparent in the DEM](https://gis.stackexchange.com/questions/285987/is-d8-flow-accumulation-algorithm-still-suitable-for-watershed-computation-if-te/286034#286034)
