### ISSUE TITLE
Inconsistent option names in the Extract Valleys tool

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-tools#38]
In the "Extract Valleys" tool there is a `--variant` parameter which accoding to the description accepts one of the following values: `LQ` (lower quartile), `JandR` (Johnston and Rosenfeld) or `PandD` (Peucker and Douglas),  and uses `LQ` as default. However in the JSON tool description available values listed in the short form, while defualt value listed in the long form `Lower Quartile`.

```
{"name":"Variant","flags":["--variant"],"description":"Options include 'LQ' (lower quartile), 'JandR' (Johnston and Rosenfeld), and 'PandD' (Peucker and Douglas); default is 'LQ'.","parameter_type":{"OptionList":["LQ","JandR","PandD"]},"default_value":"Lower Quartile","optional":false}
```

Not sure is this bug or default value was just missed during values change.

**Comment by jblindsay** [comment]
Thanks for spotting this @alexbruy. I've just committed [code](https://github.com/jblindsay/whitebox-tools/commit/f0afa0bf0b263102d073ca8480bb4696c8a5b49a) to fix this.
