### ISSUE TITLE
WhiteboxTools manual needs updating for the Geomorphons tool

### ISSUE THREAD

**Issue by simonwright-jbarisk** [jblindsay/whitebox-tools#381]
The `Geomorphons` tool has the `search`, `threshold`, `tdist` and `forms` parameters whilst the manual entry incorrectly lists the parameters `search`, `threshold`, `fdist`, `skip`, `forms` and `residuals`.

Do the `skip` and `residuals` parameters need to be removed from the user doc entry and the `fdist` parameter renamed `tdist`?

**Comment by Afrancioni** [comment]
Hi @simonwright-jbarisk 

It appears that all paramaters are listed in WhiteboxRunner. It may have been you just need to scroll down to see the skip and residual parameter. 
<img width="1208" alt="Screen Shot 2024-03-09 at 11 13 42 AM" src="https://github.com/jblindsay/whitebox-tools/assets/39802080/aac99101-c1c7-4e49-b4c8-51d31f27e8be">


As for the tdist vs fdist.. thanks for that catch!
