### ISSUE TITLE
Isochrone along direction map of watershed

### ISSUE THREAD

**Issue by GiuseppeCipolla** [jblindsay/whitebox-tools#384]
Hi everybody,

I am trying to generate a isochrone map starting from a map of the times to cross a single cell and a flow direction map. Basically, the final map has to provide, for each cell, the total time to reach the outlet of the watershed, which will be given by the sum of all the values in the cost map (i.e., the time map to cross a single cell) of the cells falling within the flow path provided by the flow direction. 

To extract the path from a point to the outlet i can use TraceDownslopeFlowPath and then through RasterCalculator I can sum all the values of my cost map of the cells along the path. However, this procedure should be repeated for all the cells of my raster.

Is there a procedure to follow or a tool that i can use? 

Best.

Giuseppe

**Comment by jblindsay** [comment]
Hi Giuseppe,

This section of the Github repo is intended for issues with the software and is not intended for general questions or discussion. Instead, please post your question to the Discussions section, or to the Google Groups email listserv. Thanks you.

Regards,

John

**Comment by GiuseppeCipolla** [comment]
Dear John, 

thank you so much for your quick reply and I am sorry for the issue. I just posted my question on both the Discussion section and the Google Groups email listserv. 

Best.

Giuseppe
