### ISSUE TITLE
ListUniqueValuesRaster

### ISSUE THREAD

**Issue by cefect** [jblindsay/whitebox-tools#386]
The documentation on this tool seems confused between whether it accepts a raster or a vector: 

![image](https://github.com/jblindsay/whitebox-tools/assets/47092034/42a5b6c2-46d4-4df9-bd2e-f4d8eed35772)

Similarly, the QGIS algorithm does not accept raster inputs. I have not tested anything else.

**Comment by jblindsay** [comment]
Good catch! I'm not sure how no one hasn't spotted that previously.

**Comment by cefect** [comment]
Thanks for the quick fix. Will this also fix the QGIS plugin? (input requirements on the drop down need to be changed to rasters)

**Comment by jblindsay** [comment]
It should also fix that, but sadly won't be available until the next release.
