### ISSUE TITLE
whitebox.Runner() urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by moxuanzhu** [jblindsay/whitebox-tools#393]
python code
  import whitebox
  whitebox.Runner()
error:urllib.error.URLError: <urlopen error unknown url type: https>,
pyhton version:3.9;windows10
how to solve?

**Comment by jblindsay** [comment]
This one would be better to post to this repo instead:

https://github.com/opengeos/whitebox-python

This repository is for the WhiteboxTools backend and your question is related to the Python frontend.
