### ISSUE TITLE
"extract_by_attribute" tool missing from "whitebox_tools.py" (?)

### ISSUE THREAD

**Issue by derrickburt** [jblindsay/whitebox-tools#404]
Hello,

Is the "extract_by_attribute" tool meant for WBT open core users?

The "extract_by_attribute" [documentation is in WBT user manual](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/gis_analysis.html#ExtractByAttribute).

<img width="264" alt="wbt_extract_by_atttribute_doc01" src="https://github.com/jblindsay/whitebox-tools/assets/69922786/3641cbf3-d856-420b-819e-96ee327efc91">
<img width="257" alt="wbt_extract_by_atttribute_doc02" src="https://github.com/jblindsay/whitebox-tools/assets/69922786/33ea16e4-13d1-4b96-9f9c-88486a982900">

But the tool's [source code is not in the GitHub repo](https://github.com/jblindsay/whitebox-tools/tree/master/whitebox-plugins/src/Extractbyattribute/main.rs).

<img width="328" alt="wbt_extract_by_atttribute_src" src="https://github.com/jblindsay/whitebox-tools/assets/69922786/bdd529be-89f1-4d44-b1db-29e7e1f18e5c">

I can't find the source code for this function: wondering if it's part of the paid WBT Toolset Extension or WbW-Pro?

Thanks!

**Comment by jblindsay** [comment]
It's part of the open core, meaning that it is in WhiteboxTools and the freeware standard tier of Whitebox Workflows for Python. Here is the source code for the WhiteboxTools version of the tool:

[https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-plugins/src/extract_by_attribute/main.rs](https://github.com/jblindsay/whitebox-tools/blob/master/whitebox-plugins/src/extract_by_attribute/main.rs)

**Comment by derrickburt** [comment]
Thank you John, much appreciated.
