### ISSUE TITLE
Breach Depressions (not fast)

### ISSUE THREAD

**Issue by kamosuela** [jblindsay/whitebox-tools#41]
Is there an updated function to do the breach depressions (the not "fast") version?

**Comment by jblindsay** [comment]
@kamosuela I just wanted to let you know that I am just now testing a port of this breaching algorithm to WhiteboxTools. I have called this tool LeastCostBreachDepressions and hope to submit it to the repo within the next few days and it will be part of the v1.0.3 release. I will close this issue at that time.

**Comment by kamosuela** [comment]
That's wonderful! Looking forward to running it

**Comment by jblindsay** [comment]
@kamosuela The new version (v1.1.0) now contains the BreachDepressionLeastCost tool, which is a modified port of the Whitebox GAT (Lindsay and Dhun, 2015) algorithm. You should find that this tool is blazing fast and provides really low-impact results for most DEMs. Please let me know what your experience is in using it. Feedback is always welcome on this type of experimental tool.
