### ISSUE TITLE
Trend Surface tool suggested improvement to documentation

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#421]
I have been exploring the Trend Surface tool, with the idea of detrending a DEM for hydrological analysis. I wanted to compare this tool against the Trend tool in ArcPro.

The help file says:

_Numerical stability is enhanced by transforming the x, y, z data by their minimum values before performing the regression analysis. These transform parameters are also reported in the output report._

To a non specialist in this subject what does _transforming the x, y, z data by their minimum values_ mean and what does that entail? Here I think the help file needs updating to explain what this means.

**Comment by jblindsay** [comment]
Thanks Duncan, I've modified it so that it states: "Numerical stability is enhanced by transforming the x, y, z data by **subtracting** their minimum values before performing the regression analysis. These transform parameters are also reported in the output report."

**Comment by asub-sandwich** [comment]
After this fix, building now raises an error in tools/lidar_analysis/ascii_to_las.rs:391:25
line_data (389) is not mutable but re-assigned at 391.

**Comment by jblindsay** [comment]
Thanks for catching that @asub-sandwich. I've just uploaded a fix for that.
