### ISSUE TITLE
WBT for QGIS Plugin 1.1.0 Removes WBT From Processing Toolbox

### ISSUE THREAD

**Issue by millsapjohn** [jblindsay/whitebox-tools#424]
When the WhiteboxTools for QGIS plugin (version 1.1.0) is installed from the QGIS Plugin Repository, the processing provider is not available in the Processing Toolbox. Reverting to plugin version 1.0.9 fixes the issue.

QGIS version: 3.38.1
WhiteboxTools for QGIS Plugin version: 1.1.0
WhiteboxTools version: 2.4.0

**Comment by jblindsay** [comment]
You need to enter the path to the whitebox_tools.exe file (or just whitebox_tools on Mac or linux) in the settings (Settings => Options => Providers => WhiteboxTools => WhiteboxTools executable). Select the path and then reload. That should then generate all of the necessary description files and you will see the plugin at that point.

**Comment by millsapjohn** [comment]
I have the executable linked, and when I check the "Recreate tool description files" box and click OK, I get the following message on the Python console:

"Can not get list of the available tools:
list index out of range"

And no processing algorithms are visible in the toolbox.

**Comment by jblindsay** [comment]
Thanks for reporting this. Are you available for a quick video chat, as it might be easier to resolve that way?

**Comment by jblindsay** [comment]
Okay, it seems that there are issues with this current version. To be honest, I'm getting pretty close to being done with trying to maintain the QGIS plugin for WhiteboxTools. It is a very problematic codebase and it has sucked a great deal of my time. Now that there is the new Whitebox Workflows QGIS plugin, I'd very much like to call the WhiteboxTools plugin legacy code and have users migrate to the WbW based plugin instead.

**Comment by millsapjohn** [comment]
My apologies for not responding earlier - I wasn't aware that the Whitebox Workflows plugin was an option! I've migrated over to that one.

Thanks for all you do developing and maintaining Whitebox.
