### ISSUE TITLE
another "panick" issue for `option::unwrap()`

### ISSUE THREAD

**Issue by emarde** [jblindsay/whitebox-tools#47]
trying to fill depressions in a DEM file. my code is below. the same thing happens when I call the 'slope' function. any thoughts on how to fix this?

wbts = wbt()
wbts.fill_depressions(dem='/Raster/DEM8m/apa8mdem',
                     output= 'apDEMfill.tif',
                     fix_flats=True)

returns:
./whitebox_tools --run="FillDepressions" --dem='/Raster/DEM8m/apa8mdem' --output='apDEMfill.tif' --fix_flats -v

******************************
* Welcome to FillDepressions *
******************************
Reading data...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

output: 0

**Comment by jblindsay** [comment]
You haven't specified a recognizable DEM file name. 'apa8mdem' doesn't have a file extension. WhiteboxTools therefore cannot read the file because it doesn't know what format it is.

**Comment by emarde** [comment]
Gotcha, thanks! And thanks for creating such a wonderful package. It's super slick.

**Comment by jblindsay** [comment]
No problem and good luck with your analysis.
