### ISSUE TITLE
VectorPolygonsToRaster issue - WhiteboxTools v1.0.0

### ISSUE THREAD

**Issue by mlavy** [jblindsay/whitebox-tools#49]
The WhiteboxTools "VectorPolygonsToRaster" still returns an output .tis with gaps.
The * Release Notes: * specify:
- Fixed a bug in the VectorPolygonsToRaster tool that sometimes mishandled polygon holes.

Does not to be fixed. See attached sample

![VectorPolygonToRaster](https://user-images.githubusercontent.com/53267230/66216324-92f53500-e6c5-11e9-95b5-044420374923.JPG)

**Comment by jblindsay** [comment]
@mlavy It would be helpful if you could forward your data set to me so that I can test the tool and find the error. The data sets that I have used to develop the tool all perform without error.

**Comment by mlavy** [comment]
> @mlavy It would be helpful if you could forward your data set to me so that I can test the tool and find the error. The data sets that I have used to develop the tool all perform without error.

I would send you the data by email using: jlindsay@uoguelph.ca
Thank you

**Comment by jblindsay** [comment]
See recent update to tool.
