### ISSUE TITLE
FlowAccumulationFullWorkflow not ignoring 'No Data'

### ISSUE THREAD

**Issue by draconigae** [jblindsay/whitebox-tools#5]
When running the 'FlowAccumulationFullWorkflow' with a geotiff DEM input,  the flow pointer and flow accumulation processes produce data in the DEM 'NoData' areas.  The 'NoData' areas are recognized in both ArcGIS and GDAL.  This particular issue does not appear in WhiteboxGAT when using the same input DEM.

I did not test on the independent d8 flow pointer and d8 flow accumulation functions.

OS: Windows 10 Pro
Python Version: 3.60
Whitebox Tools Version: 0.70

**Comment by jblindsay** [comment]
I just ran the tool on a large data set with NoData sections and it seems to have worked okay. The file was in Whitebox raster format. The NoData sections were recognized.

<img width="1104" alt="screen shot 2018-11-21 at 8 40 28 pm" src="https://user-images.githubusercontent.com/8441542/48876853-68acc880-edce-11e8-9189-952fa4d726a9.png">
