### ISSUE TITLE
Permission denied in QGIS Plugin

### ISSUE THREAD

**Issue by ghtmtt** [jblindsay/whitebox-tools#50]
Hi,

I set up the workflow as described but I cannot use the tool of Whitebox in QGIS within Processing.

These the steps I followed:

* download the tar and extracted in /home/matteo/Download
* added Alex url in QGIS to get the Processing plugin
* set up the plugin in this way:

![immagine](https://user-images.githubusercontent.com/2884884/67262911-b3373900-f4a6-11e9-97d8-bcaf8eec03a1.png)

where `WBT` is the folder containing the files of the tar

Every algorithm gives me the following error:

`/bin/sh: 1: /home/matteo/Downloads/WBT/: Permission denied`

I also tried to change the permission of the folder to 777 (but I did all the steps as normal user) and the error is still here.

OS: Linux Debian Sid, QGIS 3.9 cc @alexbruy

**Comment by giswqs** [comment]
@ghtmtt You might need to set the WBT executable to its full path, e.g., /home/matteo/Downloads/WBT/**whitebox_tools**

**Comment by ghtmtt** [comment]
oh I see now, **without** `py`. Is it worth to describe in the docs with more emphasis? 

BTW, thanks!

**Comment by matu2982** [comment]
In ubuntu 20.04 is imposible to save the path in the text box, i follow your instructions and it doesn't works, i can't use the plugin in QGIS 3.16.

**Comment by alexbruy** [comment]
Just checked and everything works fine on Windows and Linux using QGIS master and latest 3.16.

**Comment by HydrogeomorphologyTools** [comment]
Thanks, under windows the search file button to locate the executable works fine!
Attached is a screenshot.

![image](https://user-images.githubusercontent.com/13150311/207309275-43570e08-6cb6-4406-9145-10dca4166a74.png)
