### ISSUE TITLE
Add Numpy Array support

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#52]
It would be a great feature if WhiteboxTools could support Numpy Arrays both as input and output. That would simplify integration with other Python librairies and offer a way to keep the data in memory for further processing.

**Comment by jblindsay** [comment]
@jfbourdon This is a feature that I have thought about in the past as well. Unfortunately there are some serious issues with it. First, I have developed WhiteboxTools to be front-end agnostic. Many of the R-front-end users would likely not be thrilled by the idea of modifying the application in a way that only allowed for certain features when interfacing with Python. Secondly, and as a consequence of the first point, WhiteboxTools actually only interacts with the front-ends through sub-process calls (front-end to back-end) and output calls (back-end to front-end). It is not a dynamic library (DLL), and therefore cannot share more complex data structures between Python and the application. 

Early on in the application's history I experimented with different design structures that would allow for this functionality, i.e. I toyed with the idea of developing WhiteboxTools as a dynamic library that would allow for a deeper integration with Python using FFI. However, the decision was eventually made to simplify the design by making WBT a command line tool that can be easily integrated into any front-end using system subprocess calls. As such, I'm afraid that this ship has sailed.

**Comment by jfbourdon** [comment]
For anyone coming across this issue, I now use a workaround that is not always usable, but good enough when possible: a [ramdisk](https://en.wikipedia.org/wiki/RAM_drive). I use [ImDisk Toolkit (open source)](https://sourceforge.net/projects/imdisk-toolkit/) on Windows to create a ramdisk large enough to contain my intermediate files and that's it, minimal I/O times now. If you are on Linux, it's even simpler with a single command like `sudo mount -t tmpfs -o size=4096M tmpfs /media/ramdisk`.

The obvious downside is that you have less available RAM for processing, but if you have too much for what you are doing, it can work. Using a NVMe SSD is also a good option, but if you constantly write and erase gigs of data on it, it will probably shorten its lifespan.

**Comment by BjornNyberg** [comment]
Hi @jblindsay 

Just to confirm, with the new [Whitebox Workflows for Python](https://www.whiteboxgeo.com/whitebox-workflows-for-python/) or WbW-pro, is it possible to read a numpy array directly for WbW tools or a vector file from, for example, shapely? Or do these limitations apply across the entire whitebox tools?

**Comment by giswqs** [comment]
The rasterio dataset can be an alternative. It has a numpy array and associated metadata.
https://rasterio.readthedocs.io/en/latest/topics/reading.html
https://rasterio.readthedocs.io/en/stable/topics/memory-files.html

With a numpy array, resolution, crs, and transform, a GeoTIFF can be created.  
https://github.com/opengeos/leafmap/blob/master/leafmap/common.py#L10189

**Comment by cefect** [comment]
bumping this feature request. Another option could be an [xarray accessor](https://docs.xarray.dev/en/latest/internals/extending-xarray.html). Probably this would be a separate project though...
