### ISSUE TITLE
Unrecognized tool name FeaturePreservingDenoise

### ISSUE THREAD

**Issue by KeoChi** [jblindsay/whitebox-tools#54]
Hello! 
 There is one error when I use "FeaturePreservingDenoise". 
 ```
./whitebox_tools -r=FeaturePreservingDenoise -v --wd=/home/keo/nnd_storage/thirdpart_software/whitebox-tools/testdata/test_dsm/ -i=DEM_gaps_filled.tif -o=DEM_smoothed.tif --filter=15 --norm_diff=20.0 --num_iter=4
thread 'main' panicked at 'Unrecognized tool name FeaturePreservingDenoise.', src/main.rs:66:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jblindsay** [comment]
@KeoChi What front-end to WhiteboxTools are you using? Is it the QGIS, ArcGIS, Python, R front-end? Have you updated it recently? Because this tool has been renamed to FeaturePreservingSmoothing since v.1.0.0

**Comment by KeoChi** [comment]
Hello! I only use command "./whitebox_tools -r=FeaturePreservingDenoise .." in terminal. And I run "./whitebox_tools -version", then 
```
./whitebox_tools -version
WhiteboxTools v1.0.2 by Dr. John B. Lindsay (c) 2017-2019

WhiteboxTools is an advanced geospatial data analysis platform developed at
the University of Guelph's Geomorphometry and Hydrogeomatics Research 
Group (GHRG). See https://jblindsay.github.io/ghrg/WhiteboxTools/index.html
for more details
```
The version is v1.0.2.

**Comment by jblindsay** [comment]
@KeoChi The tool has been renamed to FeaturePreservingSmoothing as of v1.0.0 so you should probably just update your command line to reflect the current name.

**Comment by KeoChi** [comment]
Yes! I just found "feature_preserving_smoothing" in this whitebox_tools.py. And it can run "./whitebox_tools -r=FeaturePreservingSmoothing ..".  But I can not find the "DrainagePreservingSmoothing", has it been deleted?

**Comment by jblindsay** [comment]
@KeoChi Yes, after extensive testing of the `DrainagePreservingSmoothing` tool, it was decided that it did not offer any substantial advantage over the `FeaturePreservingSmoothing` tool and so it was removed from the list. The code is still there, it has just been disabled. If you tell me that you find the tool to be useful over-and-above the `FeaturePreservingSmoothing` tool and can demonstrate the advantage, I'd be happy to reinstate it. Please let me know.
