### ISSUE TITLE
Whiteboxtools and QGIS error while writing:

### ISSUE THREAD

**Issue by dbreckon** [jblindsay/whitebox-tools#55]
Hello, whiteboxtools v1.02, it appears the tools run but wont write to a file whether I save it to temporary file or permanent file.  Note I've reproduced the following error below with multiple tools.  This is running on Windows through QGIS.  

```
Reading data...

Saving data...

error while writing: Custom { kind: InvalidData, error: "Error while writing GeoTIFF file." }

Output file written

Elapsed Time (excluding I/O): 3.8
```

**Comment by jblindsay** [comment]
@dbreckon I'm not sure which tool you are trying to run, but would you please try to run it using the [WhiteboxRunner](https://jblindsay.github.io/wbt_book/whitebox_tools_runner.html) application instead of through the QGIS front-end. I need to know if this is an issue with the tool or with the QGIS front-end/Whitebox interface. Thanks.

**Comment by dbreckon** [comment]
Duplicated with WhiteboxRunner.  Appears to be the same issue. 

```
Smoothing normal vectors: 6.704s
Updating elevations...
Iteration 1 of 3...
Iteration 2 of 3...
Iteration 3 of 3...
Saving data...
error while writing: Custom { kind: InvalidData, error: "Error while writing GeoTIFF file." }
Output file written
Elapsed Time (excluding I/O): 12.608s
```

**Comment by jblindsay** [comment]
Okay, I'm going to need some more information. Which tool are you running? Can you please provide all of the text that is output from the tool, including the command line instruction, which usually starts ./whitebox_tools -r=...

**Comment by dbreckon** [comment]
ran the feature preserving smoothing tool and mean filter tool with same results

```
.\whitebox_tools.exe --run="Featurepreservingsmoothing" --wd="Z:\Master Files\DEM25x25tiles\Tile08" --dem='Z:\Master Files\DEM25x25tiles\Tile08\he_dem5x5.asc' --output='Z:\Master Files\DEM25x25tiles\Tile08\tempfps.tif' --filter=11 --norm_diff=15.0 --num_iter=3 --max_diff=0.5 --zfactor=1.0 -v

*****************************************
* Welcome to FeaturePreservingSmoothing *
*****************************************
Reading data...
Calculating normal vectors: 0.399s
Smoothing normal vectors: 6.497s
Updating elevations...
Iteration 1 of 3...
Iteration 2 of 3...
Iteration 3 of 3...
Saving data...
error while writing: Custom { kind: InvalidData, error: "Error while writing GeoTIFF file." }
Output file written
Elapsed Time (excluding I/O): 12.406s
```

**Comment by jblindsay** [comment]
@dbreckon Are you able to send me you DEM?

**Comment by dbreckon** [comment]
Hey John, I tried a different DEM......................and it worked!  great appears there was an issue with the DEM itself.  Thank you My apologies on wasting time. 

Dan

**Comment by jblindsay** [comment]
@dbreckon I'm concerned that it may have to do with my decoder for the asc file or the encoder for the GeoTiff file. Are you able to email me a zipped version of of your asc file? I'd still like to confirm that there isn't some bug.

**Comment by dbreckon** [comment]
Email link for file sent!
