### ISSUE TITLE
Watershed w/ raster pour_pts as input

### ISSUE THREAD

**Issue by bkielstr** [jblindsay/whitebox-tools#56]
Hoping to have Watershed enhanced so that rasters can be used as pour_pts similar to Watershed in Whitebox. This is useful for generating “lakesheds” via scripts.

**Comment by jblindsay** [comment]
@bkielstr Thank you for making this feature request. I would very much like to add this feature. The one issue that I know I will run into is that the QGIS front-end cannot handle tool input parameters that can take either a raster or vector. I've run into this issue before. However, I'll see what can be done.

**Comment by alexbruy** [comment]
@jblindsay as developer of the QGIS plugin I really appreciate that you are trying to keep WBT compatible with other programs, but if this prevents you from implementing some useful tools or making existing tools more versatile, maybe better to drop this compatibility?

Accoridng this specific question. Actually Processing allows to declare inputs as generic "layer" paramer which can be either raster, vector or even plain table. The only drawback I can think of is that with such parameter it is not possible to limit allowed geometry type (e.g. points, lines or polygons).

On other hand it is not possible to declare outputs which can be either raster or vector, however there are some workarounds. All of them require some manual work and prior knowledge of which tools are producing such outputs.

Let me know if you need more information and I will try to explain in detail.

**Comment by jblindsay** [comment]
I have just committed code that adds the ability to specify either vector points or a raster for pour points. This should resolve this issue.
