### ISSUE TITLE
How to reduce memory requirements when creating a raster grid

### ISSUE THREAD

**Issue by KeoChi** [jblindsay/whitebox-tools#58]
I use the command to create a raster grid:
  `./whitebox_tools -r=LidarTINGridding -v --wd="/whitebox-tools/testdata/" -i=pointcloud.las -o=pointcloud_dsm_tri.tif --returns=all --resolution=0.0324045`
  I found that the larger the "pointcloud.las", the greater the memory requirement. How to create a raster grid in case of limited memory? If using "LidarTile" to break a LiDAR LAS file into multiple, non-overlapping tiles and creating raster grids for every tiles. But, how to merge these grids? There are vacancies around every grid.
   Do you have good solutions?

**Comment by jblindsay** [comment]
When working with large airborne LiDAR data sets, I usually work with 1 km2 data tiles. If the data are not tiled to begin with (which they almost always are when you get them from the vendor), I do use the **LidarTile** tool to break them up, then interpolate the data, and finally I use the **Mosaic** tool to join them all together again. This workflow seems to work quite nicely for me and while my computers typically have between 16 GB to 64 GB, I have as of yet never run into an out-of-memory issue. Tiling the data works well in this regard.
