### ISSUE TITLE
BurnStreamsAtRoads

### ISSUE THREAD

**Issue by geckosl** [jblindsay/whitebox-tools#60]
I try to run the BurnStreamsAtRoads tool (in version 1.1.0) with an input DEM (almost 2000 million cells) in GeoTIFF or SAGA GIS format.
According to the manual the command is:
> ./whitebox_tools -r=BurnStreamsAtRoads -v ^
> --wd="/path/to/data/" --streams=streams.shp --base=raster.tif ^
> -o=output.tif

After replacing --base with --dem and adding --roads it worked to run the tool.

But the first two upper left pixels of the output DEM have strange values, e.g. 1.4012984643248e-45 (in the input DEM these and the adjacent ones have the NoData value of -99999).
All other pixels are shifted to the right (similar to Issue 53).
Using the input DEM in SAGA GIS format instead GeoTIFF is no alternative. The pixels where the streams are burned into the DEM have the value “-inf”.

**Comment by jblindsay** [comment]
Thank you for pointing out this issue. The example command line call function built into the tool was incorrect and has been updated [here](https://github.com/jblindsay/whitebox-tools/blob/0e678ff6a44f04033d9f9d11b7ee92aed5e51e52/src/tools/hydro_analysis/burn_streams_at_roads.rs#L110) to better reflect the flags used by the tool.
