### ISSUE TITLE
zonal_statistics out table problem

### ISSUE THREAD

**Issue by paperoses** [jblindsay/whitebox-tools#62]
when I run the zonal_statistics, there is a error: 'gbk' codec can't decode byte 0x80 in position 2839: illegal multibyte sequence, this happens only if I set the "out_table" not None. however, everthing is ok  if I run the same data in the user-interface Runner. I use Python 3.6 in Win10, anyone know the reason??

**Comment by jblindsay** [comment]
@paperoses Thank you for reporting this issue. Unfortunately I cannot seem to replicate the error. Would you be able to share your data and feature definition rasters? What front-end are you using?

**Comment by paperoses** [comment]
Thank you for your kind reply. After several trials, I found this was caused by some Chinese characters in my working directory.  After changing the directory, however, another problem arises,  after each run of zonal_statistics, Windows Explorer automatically pops up the documents folder （C: \ users \ HH \ documents）,  How to prevent it？Thank you very much.

**Comment by jblindsay** [comment]
@paperoses Does the tool not automatically display the HTML table output in your browser after completion? That is the usual behaviour. It does not open Windows Explorer by design and I can't say that I've seen this behaviour before.

**Comment by jblindsay** [comment]
This issue is caused by the use of charset=iso-8859-1 instead of UTF-8 in each of the HTML outputs of tools. Some of these tool embed input file names, including full directories. When these file names contain non-Latin characters (like the example reported above), this causes the error.
