### ISSUE TITLE
Min/Max values for classes in Reclass tool

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#67]
A suggestion to have the possibility to add `min` and `max` in the user-defined ranges the same way we can add `NoData`. Currently, if I want to reclass all values of a raster, I need to know either what is its max value or put a very high number in the last class. If the max value could be compute internally, it would save this assle (and the possibility to have it wrong). Same logic for min value. The use of max could also force a closed bracket for the last class (*Equal Or Less Than*) instead of the normal *To Just Less Than*.

**Comment by jblindsay** [comment]
This is a very good idea and an excellent usability enhancement. I've just pushed a commit to add this feature to both the Reclass and ReclassFromFile tools. Thanks for making the suggestion. You will find this new feature in the next public release of WhiteboxTools, which will hopefully be sometime next week.
