### ISSUE TITLE
Reclass (or ReclassFromFile) bug: stripping raster!

### ISSUE THREAD

**Issue by mlavy** [jblindsay/whitebox-tools#69]
The tool Reclass (or the tool ReclassFromFile) used to reclassify raster is stripping the output raster assigning erroneously strips of pixels to the first class:

Below INPUT and OUTPUT rasters

![image](https://user-images.githubusercontent.com/53267230/74148237-3ec70800-4c05-11ea-8bcb-d49e31247730.png)

![image](https://user-images.githubusercontent.com/53267230/74148248-4b4b6080-4c05-11ea-9500-a425177351c7.png)

**Comment by jblindsay** [comment]
Hi Muriel (@mlavy) thanks for raising this issue. It was very well spotted. I've just made a commit that should fix this issue. I plan to release the next version of WBT sometime early next week, which will include this fix.
