### ISSUE TITLE
Bug in Raster to Vector Polygon Tool?

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#72]
Hi John,

Keen to try out your new tools I have run the Raster to vector polygon tool on some sample data, I clipped out a tiny portion from the USA [NLCD](https://www.mrlc.gov/data?f%5B0%5D=category%3Aland%20cover&f%5B1%5D=year%3A2016) as a test, no particular reason for that location.

After getting @giswqs  to resolve an issue with the ArcGIS toolbox interface I was able to run the tool and the output seems very odd indeed. Not only do the polygons look wrong but the values they are coded with make no sense.

The input data:
![image](https://user-images.githubusercontent.com/22773948/75386451-95a53080-58d9-11ea-9509-b31335de553c.png)

The output:
![image](https://user-images.githubusercontent.com/22773948/75386521-b79eb300-58d9-11ea-876d-e8dc5b13af69.png)

The output Value field makes no sense, huge numbers:
![image](https://user-images.githubusercontent.com/22773948/75386606-e4eb6100-58d9-11ea-8c66-49bf1a0de9e1.png)

I would have expected them to be the Values (11-95) from the Value field in the raster:
![image](https://user-images.githubusercontent.com/22773948/75386711-0f3d1e80-58da-11ea-8c81-5e8eee2155cb.png)

I attach the sample data:

[testdata.zip](https://github.com/jblindsay/whitebox-tools/files/4258118/testdata.zip)

Duncan

**Comment by jblindsay** [comment]
@Hornbydd Hi Duncan. Thank you for reporting this issue. I've recently run into it myself. The polygons that I tested the tool on were quite simple in shape (watersheds) and it seems that the test data set was not very representative. Anyhow, I'm hoping to resolve this issue on Friday. There is a reason that this was one of the last tools to be ported over to WhiteboxTools. It's a very complicated operation, much more so than what most people would envision. More or less anything with vector polygons is, really. Anyhow, I'll mark this with high priority.

**Comment by Hornbydd** [comment]
I total understand, I could not even begin to understand the dark magic/wizardry you are using to create these tools! :) Also giving @giswqs  a hard time on the ArcGIS toolbox interface, only because I love it and it's my main route into using your tools. So thanks to you both and your hard work!

**Comment by jblindsay** [comment]
It's been said that I've been down to the crossroads, and fell down on my knees. But it's no dark magic...you can see the code after all. Anyhow, I'll let you know as soon as I come up with a solution. I've been thinking about one for the past three nights but haven't had a chance to try to implement it.

**Comment by jblindsay** [comment]
I just finished re-writing this tool to use a more sophisticated approach to polygon tracing. It seems to work very well in the testing that I've done. I'm closing this issue, but as always, if you encounter any further issues with the new tool, please feel free to re-open. Thanks for opening this issue in the first place. It was a hard re-write but it was well worthwhile.

**Comment by Hornbydd** [comment]
Sounds good! I'll test next week hopefully the ArcGIS toolbox version will have caught up with your latest version,
