### ISSUE TITLE
Ascii To LAS - Mentioned but not available via help or script

### ISSUE THREAD

**Issue by WalterPayne** [jblindsay/whitebox-tools#73]
Under the las_to_ascii help there is a reference to the reverse function ascii_to_las although the links seem broken.  I was unable to run the function in Python as well but the las_to_ascii seems to be functional.

[https://jblindsay.github.io/wbt_book/available_tools/lidar_tools.html](https://jblindsay.github.io/wbt_book/available_tools/lidar_tools.html)

![image](https://user-images.githubusercontent.com/8120594/75412545-c29b2700-595d-11ea-8962-7b1261d2bc54.png)

Thanks

**Comment by jblindsay** [comment]
The tool was not yet complete. I shouldn't have mentioned it in the documentation before releasing the tool. Regardless, I just committed code to the repository now that includes the new AsciiToLas tool. I'll release it in the next public version of WhiteboxTools; in the meantime you can use the tool by compiling from source. If you do so, please test the tool and let me know if you encounter any issues. Initial tested was successful.

**Comment by giswqs** [comment]
@jblindsay There is an error when compiling from source due to the missing tool `ContoursFromRaster`. I temporarily commented out the tool and was able to compile successfully. 

@WalterPayne For the time being, you can download the latest WBT binaries from [here](https://gishub.org/wbt-bin) before John releases the next public version.

**Comment by jblindsay** [comment]
@giswqs Yes, I'm afraid that I let this one slip. ContoursFromRaster is the tool that I am working on presently. It's not ready as of yet to be committed to the repository and so I left it out of the commit that I did for the AsciiToLas tool but unfortunately forgot to comment out the references to this tool in the various places required to make a tool visible. Anyhow, I've done so now and re-committed the code.
