### ISSUE TITLE
Watershed tool "thread 'main' panicked" in WBT QGIS plugin

### ISSUE THREAD

**Issue by geojohnst** [jblindsay/whitebox-tools#74]
Hello, I attempted to extract 2 watersheds from a DSM using the Watershed tool from Whitebox for Processing (plugin v0.15.0 and WBT v1.2.0) in QGIS 3.10.0. 

The DSM has undergone "BreachDepression" and a "D8Pointer" raster was created in QGIS with WBT. Using the D8Pointer raster and an esri shapefile containing 2 points as the inputs for the Watershed tool, I receive the following in the log: 

> Reading data...
>
>thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', >/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libcore\macros\mod.rs:15:40
>
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I have followed the same workflow in the WhiteboxTools Runner and got the watersheds with no issues- so it might be related to the plugin!

**Comment by duboisAM** [comment]
Hello,
I'm experiencing the same issue. but with the ArcGIS toolbox and also through the cmd prompt window. I have checked various info (projection, data extent, shp vs tif) but everything seems ok to me. The only thing is that my DEM is not hydrologically correct but this is wanted. 

The script reads the data and locates all the pour point but when it comes to initalize, it stops with the following message:

> ...
Locating pour points: 100%
Initializing: 0%
thread 'main' panicked at 'index out of bounds: the len is 129 but the index is 224', src\tools\hydro_analysis\watershed.rs:333:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Completed script Watershed...
Succeeded at Fri May  1 13:19:40 2020 (Elapsed Time: 4.15 seconds)

Although the script completes, there is no output.

As anyone come up with an explanation yet?

**Comment by fluviotect** [comment]
I'm getting the same 'index out of bounds...' error as @duboisAM 

> QGIS version: 3.16.6-Hannover
> QGIS code revision: bfd36fddc9
> Qt version: 5.11.2
> GDAL version: 3.1.4
> GEOS version: 3.8.1-CAPI-1.13.3
> PROJ version: Rel. 6.3.2, May 1st, 2020
> Processing algorithm…
> Algorithm 'Watershed' starting…
> Input parameters:
> { 'd8_pntr' : 'C:/Users/Will/AppData/Local/Temp/processing_GgKIUb/053855ad5da942f6b0616aa76850ff2d/output.tif', 'esri_pntr' : False, 'output' : 'TEMPORARY_OUTPUT', 'pour_pts' : 'D:/PhD/Data/SpatialData/WC_shapefiles/WaingawaR_CatchmentOutlet_2012.shp' }
> 
> WhiteboxTools command:
> "C:/Users/Will/GitKraken/whitebox-tools/WBT/whitebox_tools.exe" --run=Watershed --d8_pntr="C:\Users\Will\AppData\Local\Temp\processing_GgKIUb\053855ad5da942f6b0616aa76850ff2d\output.tif" --pour_pts="D:\PhD\Data\SpatialData\WC_shapefiles\WaingawaR_CatchmentOutlet_2012.shp" --esri_pntr="False" --output="C:\Users\Will\AppData\Local\Temp\processing_GgKIUb\a413ef2af4924bf496fa63d5ea79c646\output.tif" -v
> WhiteboxTools command output:
> ************************
> 
> * Welcome to Watershed *
> 
> ************************
> 
> Reading data...
> 
> thread 'main' panicked at 'index out of bounds: the len is 129 but the index is 174', whitebox-tools-app\src\tools\hydro_analysis\watershed.rs:333:58

**Comment by alexbruy** [comment]
Please provide sample data and exact steps to reproduce the issue.

P.S. Next time you discover QGIS plugin issue, please report it in the plugin bugtracker not here.

**Comment by Afrancioni** [comment]
see issue #153.
