### ISSUE TITLE
Improve support for vector formats

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#75]
Hi,

I know it explicit states in the [manual](https://jblindsay.github.io/wbt_book/supported_formats.html) that shapefiles are currently the only supported format but as an ArcGIS user  I would find it particularly useful if WBT was developed to support file geodatabase featureclasses. This would of cause require @giswqs to undo some of the validating that he has put into his python toolbox tool interfaces, but we would cross that bridge if WBT ever implements another format other than shapefiles.

As a "professional" GIS analyst I would never chose to store any data as a shapefile because of all the limitations it has. So as I build or work on a project my datasets are organised in a file geodatabase.  At some point when I need to call upon the excellent WBT I have to export out to a shapefile, loose all my crafted field names and then may be have the hassle of merging/importing WBT output back into my geodatabase.

I know it's a awful lot of work to implement robustly the use of another data format but if you ever needed an example to justify then improved workfow for ArcGIS users in one such example.

**Comment by jblindsay** [comment]
Hello Duncan,

As far as I am aware, the ArcGIS geodatabase is a proprietary format with no open specification. And so even if I had the capacity to add this feature, there is no information on which to base it. I agree that the ShapeFile is a limited vector format. However, it has a very good open specification and is widely used for data storage. Almost every software package also supports the translation of vectors into ShapeFiles. I am open to adding additional vector formats to WBT but it would likely be one of the open formats instead.

**Comment by Hornbydd** [comment]
@jblindsay  I know that the File GeoDatabase API has been made available and can be found [here](https://github.com/Esri/file-geodatabase-api). I have never needed to tinker with it and obviously there could be a whole load of technical barriers for it to work in WBT to make it unfeasible. But worth checking out?

GeoPackages seem to be a viable alternative, I understand they are SQLite databases. I get the impression they work well in QGIS but ESRI seem slow to adopt them as far as I can see they are "read only" in ArcMap so you could never use them for editing. That may change in some distant future in an alternative Universe...

**Comment by jblindsay** [comment]
@Hornbydd An open API unfortunately does not help me at all. Basically that would mean that I would need to distribute WhiteboxTools with ESRI's library for reading/writing GeoDatabases. This has several problems:  1) they likely don't have version of their DLL for all of the platforms supported by Whitebox (particularly Linux and MacOS); 2) it would tie me to a dependency that is quite large, I would think, much of the size of which would be unrelated to the actual features needed (Geodatabase encoding/decoding), 3) it's very unlikely that their library is distributed under an open-source license that is compatible with WhiteboxTools, 4) it subjects the entire WBT project to the whims of ESRI to change their proprietary format, and 5) it is a feature that really only benefits a subset of WBT users (ArcGIS users) and I have to weigh the benefits and limitations of such changes for the entire user community. I appreciate that you are working very hard to improve this project for the user community, and making some brilliant suggestions, but to me this suggestion is a non-starter. I would like to enhance my vector format support, but the ESRI format is not really a candidate for doing so.

**Comment by Hornbydd** [comment]
OK all good arguments! :)
