### ISSUE TITLE
D8FlowAccumulation ignore NoData value with --pntr flag

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#80]
It seems that the new `--pntr` flag of `D8FlowAccumulation` ignore the NoData of the D8Pointer raster as the resulting flow accumulation raster has values where it should be NoData. To reproduce with sample data from WhiteboxTools (NoData is a border all around the raster):

```
whitebox_tools -r=SetNoDataValue -i="Sample64Bit.tif" -o="DEM_nodata.tif" --back_value=9999
whitebox_tools -r=D8Pointer -i="DEM_nodata.tif" -o="D8Pointer.tif"
whitebox_tools -r=D8FlowAccumulation -i="D8Pointer.tif" -o="D8FlowAcc.tif" --pntr
```

**Comment by Afrancioni** [comment]
Closing this issue as a reference to a commit by @jblindsay on August 6th. If this issue is still persistent, I can re-open it.

**Comment by jfbourdon** [comment]
Now it's fixed.
