### ISSUE TITLE
Curious output in Merge Vector tool

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#81]
So @giswqs  has been able to resolve a bug that would not allow this tool to execute through the ArcGIS Python toolbox. I have now tested and the tool runs without error.  But...

It adds a very useful field called **Parent**, great for tracking the source of the data merge. I like it!  But it appears to be justified right with spaces up to 25 characters as shown in this screenshot

![image](https://user-images.githubusercontent.com/22773948/76011905-41b7ce80-5f0d-11ea-8b56-2fede45c6975.png)

Two things really:

1. Why is it doing this and can it be fixed? Because the first thing you will want to do is remove all the spaces!
2. Knowing that people can create long file names I think the field length should dynamically change and should not be limited to 25 characters.

I have had a look at the source code but I don't know enough about RUST language to understand what the code it doing. So I am logging this as an issue, something to be explored and fixed when you have time? I don't see this as critical but nice to resolve.

**Comment by jblindsay** [comment]
Hi Duncan, 25 characters is the length of the field. I believe that the code simply fills the unused characters with spaces. Is this not always the case with text variables in shapefile tables? I don't know how it renders in ArcGIS since I never use Arc personally. In QGIS, it looks pretty normal to me.

**Comment by jblindsay** [comment]
The DBF file specification simply states "...padded with blanks to the width of the field." for Character data. I've interpreted 'blanks' as spaces. I think that I currently add the spaces after the text, to fill out the remaining field length. I suppose it could be changed to add them at the start. Is this the convention though? Honestly, I'm not sure and the specification doesn't provide much insight into how the data should be written.

**Comment by Hornbydd** [comment]
In an attempt to respond to your question, I had to run a test again to remind myself and I've spotted something **even more troubling!**

Your code is introducing spaces before the text, this is not normal behaviour and it should not be doing it. Now you might say it's my field I'm generating, don't care.  But it is altering the text in ALL text fields by inserting leading spaces and that is fundamentally wrong as that is altering the base data!

See below , I merge aaa and bbb into ccc, a field OS_NAME is a text field see how in aaa and bbb there are no leading spaces and its left justified, this is normal expected behaviour in ArcMap. Now look at ccc see how your parent field is padded out with spaces and worse still is gone through ALL the text fields and inserted leading spaces.

![image](https://user-images.githubusercontent.com/22773948/88405043-a0032200-cdc6-11ea-80ef-eb840dea0cac.png)

**Comment by jblindsay** [comment]
Looking into it further, I see that I do in fact [add the padding spaces](https://github.com/jblindsay/whitebox-tools/blob/fe039d14f0d9c1f23ddcdfc65b274cee2713b916/src/vector/shapefile/mod.rs#L1273) to the start of the field. Again, the DBF spec doesn't actually say whether they are added at the start or end. To be clear, are you saying that you'd like to see the spaces added after the text contained in the field? If so, I can make this change.

**Comment by Hornbydd** [comment]
I and I would imagine _all other_ users, don't want any spaces added to any part of a text value in a text field. If you want to do subsequent SQL like queries then you would have to deal with all these leading/trailing spaces.

Also thinking about it any text value may already have leading or trailing spaces as part of the text value, for what ever reason, how would you distinguish between those and spaces inserted by your code? You can't! You are corrupting the data.

**Comment by jblindsay** [comment]
Okay Duncan, I've just updated the code to use trailing instead of leading padding spaces. Please give it a shot and let me know how it works for you. I'm going to close this issue now, under the assumption that this fixes the issue, but if you have any further problems with it, please feel free to re-open.

**Comment by Hornbydd** [comment]
@jblindsay - Trailing may be what we want, I guess I'll wait for the latest release of the arcgis toolbox before I can test your improvements but looking at the dbf in Notepad++ I can see that its padded as trailing spaces for the text, see below, this kind of suggests your tweaks will improve it, but until I get the latest ArcGIS toolbox I won't be able to give thumbs up.

![image](https://user-images.githubusercontent.com/22773948/88413008-57516600-cdd2-11ea-91c4-70a79a3975f8.png)

**Comment by giswqs** [comment]
@Hornbydd I just compiled WBT from source and updated the WBT Windows binary for the ArcGIS frontend. Please download the latest version from [here](https://github.com/giswqs/WhiteboxTools-ArcGIS/archive/master.zip) and let us know how it works.

**Comment by Hornbydd** [comment]
Hi @giswqs / @jblindsay ,

Downloaded the latest version of the toolbox and re-ran the Merge tool. I can confirm that ArcMap is behaving as expected now; that text is left justified and not being altered by the addition of space characters.  So thumbs up!

Thanks.

Duncan

**Comment by jblindsay** [comment]
Wonderful, I'm glad to hear that it is working as expected. Qiusheng, thanks again for your help with compiling an updated version for Duncan.
