### ISSUE TITLE
Math tool fails when second parameter is a raster

### ISSUE THREAD

**Issue by Hornbydd** [jblindsay/whitebox-tools#82]
Just been testing the ArcGIS toolbox interface for some of the raster Math tools. There is an issue and have reported that on the other website.

I have also discovered if you run the Divide tool when first parameter is a raster and the second is a value then the tool executes as expected. If the second parameter is a raster then you get the following error message:

In this test `aaa` is a raster dataset in the map document.

> Messages
> Executing: Divide DEM.tif aaa C:\Scratch\bbb.tif
> Start Time: Tue Mar 10 11:48:23 2020
> Running script Divide...
> .\whitebox_tools.exe --run="Divide" --input1='DEM.tif' --input2='aaa' --output='C:\Scratch\bbb.tif' -v
> 
> *********************
> * Welcome to Divide *
> *********************
> Reading data...
> thread 'main' panicked at 'The system cannot find the file specified. (os error 2)', src\main.rs:66:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> Completed script Divide...
> Succeeded at Tue Mar 10 11:48:23 2020 (Elapsed Time: 0.50 seconds)

I can replicate this error in the **Add**, **Multiply** and **Subtract**.

**Comment by giswqs** [comment]
@Hornbydd This is a bug caused by the ArcGIS frontend not converting the layer name to file path. The WBT backend works fine when passing the file paths. I am fixing it.

**Comment by Hornbydd** [comment]
OK
