### ISSUE TITLE
min/max in Reclass tool ignored when input is FLT file

### ISSUE THREAD

**Issue by jfbourdon** [jblindsay/whitebox-tools#90]
The newly introduced min/max (1.2.0) in the reclass string is ignored when using FLT file as input. I made the following tests:
- TIF to TIF: ok, but max value itself excluded from the reclassification
- TIF to FLT: ok, but max value itself excluded from the reclassification
- FLT to FLT: min and max string not considered
- FLT to TIF: min and max string not considered

I mean by "min and max string not considered", that if I have
`--reclass_vals='1;min;500;2;500;1000;3;1000;max'`, only the values [500,1000[ will be converted to 2, all others values being unchanged.

The max value itseft being excluded is a separate issue, but I noticed it at the same time. I suppose that is because by default the second value of each class is always excluded. I think however that an exception should be made when using "max".

**Comment by jblindsay** [comment]
Thanks for reporting this issue. The FLT reader was not scanning the raster to set the min/max values (it's not stored in the header file) and that was what caused this particular error. I just committed a fix that should resolve this issue.
