### ISSUE TITLE
whitebox for processing v.1.0.0

### ISSUE THREAD

**Issue by pedrodrigues2020** [jblindsay/whitebox-tools#91]
I had try to put "WhiteboxTools for Processing 1.0.0" qgis plugin on QGIS 3.10 long term realese and don´t apear on plugins list to install then i can't use whitebox tools on QGIS 3.10 long term realese, i think the last version (1.0.0) of this plugin only works on Qgis 3.12. 

Is it possible to obtain one version work on QGIS 3.10 long term realese?

**Comment by jblindsay** [comment]
This is an issue for the QGIS front-end, not the WBT back-end project. Please raise this issue in the Whitebox for processing repository instead.
