### ISSUE TITLE
could not find watershed tool from whitebox-tools QGIS plugin

### ISSUE THREAD

**Issue by yhan27** [jblindsay/whitebox-tools#92]
I installed the latest WBT QGIS plugin (https://plugins.bruy.me/plugins/plugins.xml#whitebox) and WBT itself. Everything is working fine but I could not find the watershed tool. Any thought?

**Comment by jblindsay** [comment]
This is an issue for the QGIS Whitebox front-end, not the WBT backend. The watershed tool is listed in the backend and is accessible from the Whitebox Runner application (and the Python API). I am closing this issue now but feel free to raise the issue with Alex, who maintains the Q front end.
