### ISSUE TITLE
Error while trying to process a moderately big Geotiff raster - tools can process small rasters

### ISSUE THREAD

**Issue by alherca73** [jblindsay/whitebox-tools#96]
Hi, I am getting this error when trying to use several of the geospatial and hydrological tools. The raster is 10,900 rows x 15100 columns INT16.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "Invalid code 202, expected code <= 1FF" }', src/raster/geotiff/mod.rs:1113:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have no idea what the error means.

Thanks for any help.

Alex

**Comment by jblindsay** [comment]
@alherca73 Can you give me a bit more information? Which tools did you receive this error on? Is this an error that you received using the latest release of WBT? If so, have you run into a similar error using this data set on a previous release? Are you able to share your data set for testing?

**Comment by alherca73** [comment]
Hi @jblindsay. After numerous tries, it became clear that WBT did not like to use integer rasters but only Floating rasters. It was pure chance that I decided to try the same processes with a Floating raster, and it worked. Thanks!!! WBT rocks!

**Comment by jblindsay** [comment]
Which tools were you specifically using? WBT really should be able to read and write GeoTIFFs in integer formats and so this is a bug if you are experiencing this. It would be helpful if I could know which tools you encountered this error for. Thanks.

**Comment by alherca73** [comment]
Hi again. First I was using (in R package but then tried Python and kept getting same error message) wbt_clip_raster_to_polygon. I also experienced the same error using the hydrological tools wbt_fill_depressions. Like I mentioned before, as soon as I used a Floating raster it worked. Thanks for your help.

**Comment by alherca73** [comment]
Hello. Any updates if WBT can use integer rasters for processing? It would help for disk space. Thanks for your help.

**Comment by jblindsay** [comment]
@alherca73 WBT does handle integer rasters. For example, I am currently using the Hillshade tool for a project and am saving the output file in a 16-bit integer GeoTIFF without any issue. As for the fill depressions tool, well no, it doesn't make sense for it to have an integer output. After all, to correct the flat areas produced by depression filling requires adding small elevation increments that must be stored in a floating point output.

 I'm afraid that you haven't provided me enough information here to resolve your issue. You didn't tell me what tool specifically produced the original error that you reported. I suspect that it isn't an issue with the tool, but rather an issue with the GeoTIFF reader. WBT's GeoTIFF reader is not as mature as GDAL or Esri's and therefore doesn't currently support certain types of GeoTIFFs. For example, certain types of compressed or tiled GeoTIFFs may cause issues. You could help me to make the reader more robust if you are able to share the problematic file with me. Please consider forwarding your file to me.

**Comment by jblindsay** [comment]
After spending some time working on this, I have determined that the "Invalid code 202, expected code <= 1FF" error was being thrown by the LZW compression library that I was using in my GeoTIFF reader. I have since resolved this issue. With this most recent commit, this error should now be resolved.
