### ISSUE TITLE
Result of FeaturePreservingSmoothing is corrupted for GeoTIFFs created with PREDICTOR=3

### ISSUE THREAD

**Issue by zdila** [jblindsay/whitebox-tools#97]
Result of FeaturePreservingSmoothing is corrupted for GeoTIFFs created with `-co PREDICTOR=3`:

```
gdalwarp -overwrite -of GTiff -ot Float32 -co TILED=YES -co BIGTIFF=YES -co COMPRESS=LZW -co PREDICTOR=3 -co NUM_THREADS=ALL_CPUS -wo NUM_THREADS=ALL_CPUS -multi -r cubicspline -order 3 -tr 19.109257071294062687 19.109257071294062687 -tap -t_srs "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over" N47E020.HGT N47E020.tif

whitebox_tools -r=FeaturePreservingSmoothing -v --wd="." --dem=N47E020.tif -o=test.tif --filter=15 --norm_diff=20.0 --num_iter=4
```

Result:

![image](https://user-images.githubusercontent.com/636095/85983851-839ee000-b9e8-11ea-9bf1-76c510831f63.png)

Without providing `-co PREDICTOR=3` the result is fine.

**Comment by jblindsay** [comment]
The WBT GeoTIFF reader does not support float-point predictors. I've just made a commit that will result in a more graceful error message when predictor 3 is used. Predictor 2 is however supported.

**Comment by jfbourdon** [comment]
I just encountered the same issue but with DEFLATE (predictor 2 or 3) when reading GeoTiff. Predictor 1 is fine however. Is predictor 2 with LZW only supported in the next release? Everything tested on v1.3.0.

**Comment by jblindsay** [comment]
The fix will come in the next release, sometime this week. Predictor 3 will not be supported, but the library will issue a human-readable error message indicating this fact so users at least have some guidance. Predictor 2 should work; at least it is working on the development branch on my tests.
