### ISSUE TITLE
CentroidVector loose attribute table & PolygonArea return negative value

### ISSUE THREAD

**Issue by mlavy** [jblindsay/whitebox-tools#99]
The tool centroid_vector run over shapefile returns the output centroid shapefile loosing all the attributes from the original input vector:

```
wbt.centroid_vector(
    i="polygons.shp", 
    output="centroids.shp", 
)
```

only the FID field and the geometry is correct.

The tool polygon_area run over shapefile polygon in UTM projection (1 feature) returns a negative value:

```
wbt.polygon_area(
    i="boundary_bbox.shp",
)

```

Notes:
Running on Windows 10

[wbt.zip](https://github.com/jblindsay/whitebox-tools/files/4937862/wbt.zip)

**Comment by jblindsay** [comment]
I've just committed code to provide a fix for this issue for both the CentroidVector and the Mediod tools. Please let me know if you have any further issues. I am closing this issue now but feel free to re-open if you encounter any further problems.
